import React, { useState } from "react";
import HomePage from "./homepage";
import moment from "moment";
import { useDispatch, useSelector } from "react-redux";

export default HomepageContainer = (props) => {
  const { token, profileDetail, reload } = useSelector((state) => ({
    token: state.token.token,
    profileDetail: state.profileDetail.profileDetail,
    reload: state.reload.reload,
  }));

  const [day, setDay] = useState("3");

  const labelByDay = (today) => {
    switch (today) {
      case 1:
        return {
          label: ["Label", "F", "S", "S", "M", "T", "W", "T"],
          data: [
            [
              { time: "1:00 AM", value: 2 },
              { time: "2:00 AM", value: 1 },
              { time: "3:00 AM", value: 1 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 4 },
              { time: "7:00 AM", value: 1 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 2 },
              { time: "10:00 AM", value: 5 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 1 },
              { time: "1:00 pm", value: 1 },
              { time: "2:00 pm", value: 2 },
              { time: "3:00 pm", value: 5 },
              { time: "4:00 pm", value: 5 },
              { time: "5:00 pm", value: 2 },
              { time: "6:00 pm", value: 2 },
              { time: "7:00 pm", value: 2 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 5 },
              { time: "10:00 pm", value: 4 },
              { time: "11:00 pm", value: 2 },
              { time: "12:00 pm", value: 0 },
            ],
            [
              { time: "1:00 AM", value: 0 },
              { time: "2:00 AM", value: 0 },
              { time: "3:00 AM", value: 0 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 0 },
              { time: "7:00 AM", value: 0 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 0 },
              { time: "10:00 AM", value: 0 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 0 },
              { time: "1:00 pm", value: 0 },
              { time: "2:00 pm", value: 0 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 0 },
              { time: "5:00 pm", value: 0 },
              { time: "6:00 pm", value: 0 },
              { time: "7:00 pm", value: 0 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 0 },
              { time: "10:00 pm", value: 0 },
              { time: "11:00 pm", value: 0 },
              { time: "12:00 pm", value: 0 },
            ],
            [
              { time: "1:00 AM", value: 0 },
              { time: "2:00 AM", value: 0 },
              { time: "3:00 AM", value: 0 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 0 },
              { time: "7:00 AM", value: 0 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 0 },
              { time: "10:00 AM", value: 0 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 0 },
              { time: "1:00 pm", value: 0 },
              { time: "2:00 pm", value: 0 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 0 },
              { time: "5:00 pm", value: 0 },
              { time: "6:00 pm", value: 0 },
              { time: "7:00 pm", value: 0 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 0 },
              { time: "10:00 pm", value: 0 },
              { time: "11:00 pm", value: 0 },
              { time: "12:00 pm", value: 0 },
            ],
            [
              { time: "1:00 AM", value: 0 },
              { time: "2:00 AM", value: 0 },
              { time: "3:00 AM", value: 0 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 0 },
              { time: "7:00 AM", value: 0 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 0 },
              { time: "10:00 AM", value: 0 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 0 },
              { time: "1:00 pm", value: 0 },
              { time: "2:00 pm", value: 0 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 0 },
              { time: "5:00 pm", value: 0 },
              { time: "6:00 pm", value: 0 },
              { time: "7:00 pm", value: 0 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 0 },
              { time: "10:00 pm", value: 0 },
              { time: "11:00 pm", value: 0 },
              { time: "12:00 pm", value: 0 },
            ],
            [
              { time: "1:00 AM", value: 0 },
              { time: "2:00 AM", value: 0 },
              { time: "3:00 AM", value: 0 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 3 },
              { time: "7:00 AM", value: 3 },
              { time: "8:00 AM", value: 3 },
              { time: "9:00 AM", value: 3 },
              { time: "10:00 AM", value: 3 },
              { time: "11:00 AM", value: 3 },
              { time: "12:00 AM", value: 3 },
              { time: "1:00 pm", value: 0 },
              { time: "2:00 pm", value: 0 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 0 },
              { time: "5:00 pm", value: 0 },
              { time: "6:00 pm", value: 0 },
              { time: "7:00 pm", value: 0 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 5 },
              { time: "10:00 pm", value: 5 },
              { time: "11:00 pm", value: 5 },
              { time: "12:00 pm", value: 5 },
            ],
            [
              { time: "1:00 AM", value: 0 },
              { time: "2:00 AM", value: 0 },
              { time: "3:00 AM", value: 0 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 0 },
              { time: "7:00 AM", value: 0 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 0 },
              { time: "10:00 AM", value: 0 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 0 },
              { time: "1:00 pm", value: 0 },
              { time: "2:00 pm", value: 0 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 0 },
              { time: "5:00 pm", value: 0 },
              { time: "6:00 pm", value: 0 },
              { time: "7:00 pm", value: 0 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 0 },
              { time: "10:00 pm", value: 0 },
              { time: "11:00 pm", value: 0 },
              { time: "12:00 pm", value: 0 },
            ],
            [
              { time: "1:00 AM", value: 0 },
              { time: "2:00 AM", value: 0 },
              { time: "3:00 AM", value: 0 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 0 },
              { time: "7:00 AM", value: 0 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 0 },
              { time: "10:00 AM", value: 0 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 0 },
              { time: "1:00 pm", value: 0 },
              { time: "2:00 pm", value: 0 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 0 },
              { time: "5:00 pm", value: 0 },
              { time: "6:00 pm", value: 0 },
              { time: "7:00 pm", value: 0 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 0 },
              { time: "10:00 pm", value: 0 },
              { time: "11:00 pm", value: 0 },
              { time: "12:00 pm", value: 0 },
            ],
            [
              { time: "1:00 AM", value: 0 },
              { time: "2:00 AM", value: 0 },
              { time: "3:00 AM", value: 0 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 0 },
              { time: "7:00 AM", value: 0 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 0 },
              { time: "10:00 AM", value: 0 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 0 },
              { time: "1:00 pm", value: 0 },
              { time: "2:00 pm", value: 0 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 0 },
              { time: "5:00 pm", value: 0 },
              { time: "6:00 pm", value: 0 },
              { time: "7:00 pm", value: 0 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 0 },
              { time: "10:00 pm", value: 0 },
              { time: "11:00 pm", value: 0 },
              { time: "12:00 pm", value: 0 },
            ],
          ],
        };
      case 2:
        return {
          label: ["Label", "S", "S", "M", "T", "W", "T", "F"],
          data: [
            [
              { time: "1:00 AM", value: 2 },
              { time: "2:00 AM", value: 1 },
              { time: "3:00 AM", value: 1 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 4 },
              { time: "7:00 AM", value: 1 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 2 },
              { time: "10:00 AM", value: 5 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 1 },
              { time: "1:00 pm", value: 1 },
              { time: "2:00 pm", value: 2 },
              { time: "3:00 pm", value: 5 },
              { time: "4:00 pm", value: 5 },
              { time: "5:00 pm", value: 2 },
              { time: "6:00 pm", value: 2 },
              { time: "7:00 pm", value: 2 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 5 },
              { time: "10:00 pm", value: 4 },
              { time: "11:00 pm", value: 2 },
              { time: "12:00 pm", value: 0 },
            ],
            [
              { time: "1:00 AM", value: 0 },
              { time: "2:00 AM", value: 0 },
              { time: "3:00 AM", value: 0 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 0 },
              { time: "7:00 AM", value: 0 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 0 },
              { time: "10:00 AM", value: 0 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 0 },
              { time: "1:00 pm", value: 0 },
              { time: "2:00 pm", value: 0 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 0 },
              { time: "5:00 pm", value: 0 },
              { time: "6:00 pm", value: 0 },
              { time: "7:00 pm", value: 0 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 0 },
              { time: "10:00 pm", value: 0 },
              { time: "11:00 pm", value: 0 },
              { time: "12:00 pm", value: 0 },
            ],
            [
              { time: "1:00 AM", value: 0 },
              { time: "2:00 AM", value: 0 },
              { time: "3:00 AM", value: 0 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 0 },
              { time: "7:00 AM", value: 0 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 0 },
              { time: "10:00 AM", value: 0 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 0 },
              { time: "1:00 pm", value: 0 },
              { time: "2:00 pm", value: 0 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 0 },
              { time: "5:00 pm", value: 0 },
              { time: "6:00 pm", value: 0 },
              { time: "7:00 pm", value: 0 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 0 },
              { time: "10:00 pm", value: 0 },
              { time: "11:00 pm", value: 0 },
              { time: "12:00 pm", value: 0 },
            ],
            [
              { time: "1:00 AM", value: 0 },
              { time: "2:00 AM", value: 0 },
              { time: "3:00 AM", value: 0 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 0 },
              { time: "7:00 AM", value: 0 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 0 },
              { time: "10:00 AM", value: 0 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 0 },
              { time: "1:00 pm", value: 0 },
              { time: "2:00 pm", value: 0 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 0 },
              { time: "5:00 pm", value: 0 },
              { time: "6:00 pm", value: 0 },
              { time: "7:00 pm", value: 0 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 0 },
              { time: "10:00 pm", value: 0 },
              { time: "11:00 pm", value: 0 },
              { time: "12:00 pm", value: 0 },
            ],
            [
              { time: "1:00 AM", value: 0 },
              { time: "2:00 AM", value: 0 },
              { time: "3:00 AM", value: 1 },
              { time: "4:00 AM", value: 1 },
              { time: "5:00 AM", value: 1 },
              { time: "6:00 AM", value: 1 },
              { time: "7:00 AM", value: 1 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 0 },
              { time: "10:00 AM", value: 0 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 4 },
              { time: "1:00 pm", value: 4 },
              { time: "2:00 pm", value: 4 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 0 },
              { time: "5:00 pm", value: 0 },
              { time: "6:00 pm", value: 0 },
              { time: "7:00 pm", value: 0 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 5 },
              { time: "10:00 pm", value: 5 },
              { time: "11:00 pm", value: 5 },
              { time: "12:00 pm", value: 5 },
            ],
            [
              { time: "1:00 AM", value: 0 },
              { time: "2:00 AM", value: 0 },
              { time: "3:00 AM", value: 0 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 0 },
              { time: "7:00 AM", value: 0 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 0 },
              { time: "10:00 AM", value: 0 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 0 },
              { time: "1:00 pm", value: 0 },
              { time: "2:00 pm", value: 0 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 0 },
              { time: "5:00 pm", value: 0 },
              { time: "6:00 pm", value: 0 },
              { time: "7:00 pm", value: 0 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 0 },
              { time: "10:00 pm", value: 0 },
              { time: "11:00 pm", value: 0 },
              { time: "12:00 pm", value: 0 },
            ],
            [
              { time: "1:00 AM", value: 0 },
              { time: "2:00 AM", value: 0 },
              { time: "3:00 AM", value: 0 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 0 },
              { time: "7:00 AM", value: 0 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 0 },
              { time: "10:00 AM", value: 0 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 0 },
              { time: "1:00 pm", value: 0 },
              { time: "2:00 pm", value: 0 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 0 },
              { time: "5:00 pm", value: 0 },
              { time: "6:00 pm", value: 0 },
              { time: "7:00 pm", value: 0 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 0 },
              { time: "10:00 pm", value: 0 },
              { time: "11:00 pm", value: 0 },
              { time: "12:00 pm", value: 0 },
            ],
            [
              { time: "1:00 AM", value: 0 },
              { time: "2:00 AM", value: 0 },
              { time: "3:00 AM", value: 0 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 0 },
              { time: "7:00 AM", value: 0 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 0 },
              { time: "10:00 AM", value: 0 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 0 },
              { time: "1:00 pm", value: 0 },
              { time: "2:00 pm", value: 0 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 0 },
              { time: "5:00 pm", value: 0 },
              { time: "6:00 pm", value: 0 },
              { time: "7:00 pm", value: 0 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 0 },
              { time: "10:00 pm", value: 0 },
              { time: "11:00 pm", value: 0 },
              { time: "12:00 pm", value: 0 },
            ],
          ],
        };

      case 3:
        return {
          label: ["Label", "S", "M", "W", "W", "T", "F", "S"],
          data: [
            [
              { time: "1:00 AM", value: 2 },
              { time: "2:00 AM", value: 1 },
              { time: "3:00 AM", value: 1 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 4 },
              { time: "7:00 AM", value: 1 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 2 },
              { time: "10:00 AM", value: 5 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 1 },
              { time: "1:00 pm", value: 1 },
              { time: "2:00 pm", value: 2 },
              { time: "3:00 pm", value: 5 },
              { time: "4:00 pm", value: 5 },
              { time: "5:00 pm", value: 2 },
              { time: "6:00 pm", value: 2 },
              { time: "7:00 pm", value: 2 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 5 },
              { time: "10:00 pm", value: 4 },
              { time: "11:00 pm", value: 2 },
              { time: "12:00 pm", value: 0 },
            ],
            [
              { time: "1:00 AM", value: 0 },
              { time: "2:00 AM", value: 0 },
              { time: "3:00 AM", value: 0 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 0 },
              { time: "7:00 AM", value: 0 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 0 },
              { time: "10:00 AM", value: 0 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 0 },
              { time: "1:00 pm", value: 0 },
              { time: "2:00 pm", value: 0 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 0 },
              { time: "5:00 pm", value: 0 },
              { time: "6:00 pm", value: 0 },
              { time: "7:00 pm", value: 0 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 0 },
              { time: "10:00 pm", value: 0 },
              { time: "11:00 pm", value: 0 },
              { time: "12:00 pm", value: 0 },
            ],
            [
              { time: "1:00 AM", value: 0 },
              { time: "2:00 AM", value: 0 },
              { time: "3:00 AM", value: 0 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 0 },
              { time: "7:00 AM", value: 0 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 0 },
              { time: "10:00 AM", value: 0 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 0 },
              { time: "1:00 pm", value: 0 },
              { time: "2:00 pm", value: 0 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 0 },
              { time: "5:00 pm", value: 0 },
              { time: "6:00 pm", value: 0 },
              { time: "7:00 pm", value: 0 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 0 },
              { time: "10:00 pm", value: 0 },
              { time: "11:00 pm", value: 0 },
              { time: "12:00 pm", value: 0 },
            ],
            [
              { time: "1:00 AM", value: 0 },
              { time: "2:00 AM", value: 0 },
              { time: "3:00 AM", value: 0 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 0 },
              { time: "7:00 AM", value: 0 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 0 },
              { time: "10:00 AM", value: 0 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 0 },
              { time: "1:00 pm", value: 0 },
              { time: "2:00 pm", value: 0 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 0 },
              { time: "5:00 pm", value: 0 },
              { time: "6:00 pm", value: 0 },
              { time: "7:00 pm", value: 0 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 0 },
              { time: "10:00 pm", value: 0 },
              { time: "11:00 pm", value: 0 },
              { time: "12:00 pm", value: 0 },
            ],
            [
              { time: "1:00 AM", value: 3 },
              { time: "2:00 AM", value: 3 },
              { time: "3:00 AM", value: 3 },
              { time: "4:00 AM", value: 3 },
              { time: "5:00 AM", value: 3 },
              { time: "6:00 AM", value: 3 },
              { time: "7:00 AM", value: 0 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 0 },
              { time: "10:00 AM", value: 0 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 0 },
              { time: "1:00 pm", value: 0 },
              { time: "2:00 pm", value: 0 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 0 },
              { time: "5:00 pm", value: 2 },
              { time: "6:00 pm", value: 2 },
              { time: "7:00 pm", value: 2 },
              { time: "8:00 pm", value: 2 },
              { time: "9:00 pm", value: 0 },
              { time: "10:00 pm", value: 0 },
              { time: "11:00 pm", value: 0 },
              { time: "12:00 pm", value: 0 },
            ],
            [
              { time: "1:00 AM", value: 0 },
              { time: "2:00 AM", value: 0 },
              { time: "3:00 AM", value: 0 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 0 },
              { time: "7:00 AM", value: 0 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 0 },
              { time: "10:00 AM", value: 0 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 0 },
              { time: "1:00 pm", value: 0 },
              { time: "2:00 pm", value: 0 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 0 },
              { time: "5:00 pm", value: 0 },
              { time: "6:00 pm", value: 0 },
              { time: "7:00 pm", value: 0 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 0 },
              { time: "10:00 pm", value: 0 },
              { time: "11:00 pm", value: 0 },
              { time: "12:00 pm", value: 0 },
            ],
            [
              { time: "1:00 AM", value: 0 },
              { time: "2:00 AM", value: 0 },
              { time: "3:00 AM", value: 0 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 0 },
              { time: "7:00 AM", value: 0 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 0 },
              { time: "10:00 AM", value: 0 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 0 },
              { time: "1:00 pm", value: 0 },
              { time: "2:00 pm", value: 0 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 0 },
              { time: "5:00 pm", value: 0 },
              { time: "6:00 pm", value: 0 },
              { time: "7:00 pm", value: 0 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 0 },
              { time: "10:00 pm", value: 0 },
              { time: "11:00 pm", value: 0 },
              { time: "12:00 pm", value: 0 },
            ],
            [
              { time: "1:00 AM", value: 0 },
              { time: "2:00 AM", value: 0 },
              { time: "3:00 AM", value: 0 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 0 },
              { time: "7:00 AM", value: 0 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 0 },
              { time: "10:00 AM", value: 0 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 0 },
              { time: "1:00 pm", value: 0 },
              { time: "2:00 pm", value: 0 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 0 },
              { time: "5:00 pm", value: 0 },
              { time: "6:00 pm", value: 0 },
              { time: "7:00 pm", value: 0 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 0 },
              { time: "10:00 pm", value: 0 },
              { time: "11:00 pm", value: 0 },
              { time: "12:00 pm", value: 0 },
            ],
          ],
        };

      case 4:
        return {
          label: ["Label", "M", "T", "W", "T", "F", "S", "S"],
          data: [
            [
              { time: "1:00 AM", value: 2 },
              { time: "2:00 AM", value: 1 },
              { time: "3:00 AM", value: 1 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 4 },
              { time: "7:00 AM", value: 1 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 2 },
              { time: "10:00 AM", value: 5 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 1 },
              { time: "1:00 pm", value: 1 },
              { time: "2:00 pm", value: 2 },
              { time: "3:00 pm", value: 5 },
              { time: "4:00 pm", value: 5 },
              { time: "5:00 pm", value: 2 },
              { time: "6:00 pm", value: 2 },
              { time: "7:00 pm", value: 2 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 5 },
              { time: "10:00 pm", value: 4 },
              { time: "11:00 pm", value: 2 },
              { time: "12:00 pm", value: 0 },
            ],
            [
              { time: "1:00 AM", value: 0 },
              { time: "2:00 AM", value: 0 },
              { time: "3:00 AM", value: 0 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 0 },
              { time: "7:00 AM", value: 0 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 0 },
              { time: "10:00 AM", value: 0 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 0 },
              { time: "1:00 pm", value: 0 },
              { time: "2:00 pm", value: 0 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 0 },
              { time: "5:00 pm", value: 0 },
              { time: "6:00 pm", value: 0 },
              { time: "7:00 pm", value: 0 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 0 },
              { time: "10:00 pm", value: 0 },
              { time: "11:00 pm", value: 0 },
              { time: "12:00 pm", value: 0 },
            ],
            [
              { time: "1:00 AM", value: 0 },
              { time: "2:00 AM", value: 0 },
              { time: "3:00 AM", value: 0 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 0 },
              { time: "7:00 AM", value: 0 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 0 },
              { time: "10:00 AM", value: 0 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 0 },
              { time: "1:00 pm", value: 0 },
              { time: "2:00 pm", value: 0 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 0 },
              { time: "5:00 pm", value: 0 },
              { time: "6:00 pm", value: 0 },
              { time: "7:00 pm", value: 0 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 0 },
              { time: "10:00 pm", value: 0 },
              { time: "11:00 pm", value: 0 },
              { time: "12:00 pm", value: 0 },
            ],
            [
              { time: "1:00 AM", value: 0 },
              { time: "2:00 AM", value: 0 },
              { time: "3:00 AM", value: 0 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 0 },
              { time: "7:00 AM", value: 0 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 0 },
              { time: "10:00 AM", value: 0 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 0 },
              { time: "1:00 pm", value: 0 },
              { time: "2:00 pm", value: 0 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 0 },
              { time: "5:00 pm", value: 0 },
              { time: "6:00 pm", value: 0 },
              { time: "7:00 pm", value: 0 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 0 },
              { time: "10:00 pm", value: 0 },
              { time: "11:00 pm", value: 0 },
              { time: "12:00 pm", value: 0 },
            ],
            [
              { time: "1:00 AM", value: 0 },
              { time: "2:00 AM", value: 0 },
              { time: "3:00 AM", value: 0 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 0 },
              { time: "7:00 AM", value: 0 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 0 },
              { time: "10:00 AM", value: 1 },
              { time: "11:00 AM", value: 1 },
              { time: "12:00 AM", value: 1 },
              { time: "1:00 pm", value: 1 },
              { time: "2:00 pm", value: 1 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 0 },
              { time: "5:00 pm", value: 0 },
              { time: "6:00 pm", value: 0 },
              { time: "7:00 pm", value: 0 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 5 },
              { time: "10:00 pm", value: 5 },
              { time: "11:00 pm", value: 5 },
              { time: "12:00 pm", value: 5 },
            ],
            [
              { time: "1:00 AM", value: 0 },
              { time: "2:00 AM", value: 0 },
              { time: "3:00 AM", value: 0 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 0 },
              { time: "7:00 AM", value: 0 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 0 },
              { time: "10:00 AM", value: 0 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 0 },
              { time: "1:00 pm", value: 0 },
              { time: "2:00 pm", value: 0 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 0 },
              { time: "5:00 pm", value: 0 },
              { time: "6:00 pm", value: 0 },
              { time: "7:00 pm", value: 0 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 0 },
              { time: "10:00 pm", value: 0 },
              { time: "11:00 pm", value: 0 },
              { time: "12:00 pm", value: 0 },
            ],
            [
              { time: "1:00 AM", value: 0 },
              { time: "2:00 AM", value: 0 },
              { time: "3:00 AM", value: 0 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 0 },
              { time: "7:00 AM", value: 0 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 0 },
              { time: "10:00 AM", value: 0 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 0 },
              { time: "1:00 pm", value: 0 },
              { time: "2:00 pm", value: 0 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 0 },
              { time: "5:00 pm", value: 0 },
              { time: "6:00 pm", value: 0 },
              { time: "7:00 pm", value: 0 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 0 },
              { time: "10:00 pm", value: 0 },
              { time: "11:00 pm", value: 0 },
              { time: "12:00 pm", value: 0 },
            ],
            [
              { time: "1:00 AM", value: 0 },
              { time: "2:00 AM", value: 0 },
              { time: "3:00 AM", value: 0 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 0 },
              { time: "7:00 AM", value: 0 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 0 },
              { time: "10:00 AM", value: 0 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 0 },
              { time: "1:00 pm", value: 0 },
              { time: "2:00 pm", value: 0 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 0 },
              { time: "5:00 pm", value: 0 },
              { time: "6:00 pm", value: 0 },
              { time: "7:00 pm", value: 0 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 0 },
              { time: "10:00 pm", value: 0 },
              { time: "11:00 pm", value: 0 },
              { time: "12:00 pm", value: 0 },
            ],
          ],
        };

      case 5:
        return {
          label: ["Label", "T", "W", "T", "F", "S", "S", "M"],
          data: [
            [
              { time: "1:00 AM", value: 2 },
              { time: "2:00 AM", value: 1 },
              { time: "3:00 AM", value: 1 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 4 },
              { time: "7:00 AM", value: 1 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 2 },
              { time: "10:00 AM", value: 5 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 1 },
              { time: "1:00 pm", value: 1 },
              { time: "2:00 pm", value: 2 },
              { time: "3:00 pm", value: 5 },
              { time: "4:00 pm", value: 5 },
              { time: "5:00 pm", value: 2 },
              { time: "6:00 pm", value: 2 },
              { time: "7:00 pm", value: 2 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 5 },
              { time: "10:00 pm", value: 4 },
              { time: "11:00 pm", value: 2 },
              { time: "12:00 pm", value: 0 },
            ],
            [
              { time: "1:00 AM", value: 0 },
              { time: "2:00 AM", value: 0 },
              { time: "3:00 AM", value: 0 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 0 },
              { time: "7:00 AM", value: 0 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 0 },
              { time: "10:00 AM", value: 0 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 0 },
              { time: "1:00 pm", value: 0 },
              { time: "2:00 pm", value: 0 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 0 },
              { time: "5:00 pm", value: 0 },
              { time: "6:00 pm", value: 0 },
              { time: "7:00 pm", value: 0 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 0 },
              { time: "10:00 pm", value: 0 },
              { time: "11:00 pm", value: 0 },
              { time: "12:00 pm", value: 0 },
            ],
            [
              { time: "1:00 AM", value: 0 },
              { time: "2:00 AM", value: 0 },
              { time: "3:00 AM", value: 0 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 0 },
              { time: "7:00 AM", value: 0 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 0 },
              { time: "10:00 AM", value: 0 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 0 },
              { time: "1:00 pm", value: 0 },
              { time: "2:00 pm", value: 0 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 0 },
              { time: "5:00 pm", value: 0 },
              { time: "6:00 pm", value: 0 },
              { time: "7:00 pm", value: 0 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 0 },
              { time: "10:00 pm", value: 0 },
              { time: "11:00 pm", value: 0 },
              { time: "12:00 pm", value: 0 },
            ],
            [
              { time: "1:00 AM", value: 0 },
              { time: "2:00 AM", value: 0 },
              { time: "3:00 AM", value: 0 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 0 },
              { time: "7:00 AM", value: 0 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 0 },
              { time: "10:00 AM", value: 0 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 0 },
              { time: "1:00 pm", value: 0 },
              { time: "2:00 pm", value: 0 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 0 },
              { time: "5:00 pm", value: 0 },
              { time: "6:00 pm", value: 0 },
              { time: "7:00 pm", value: 0 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 0 },
              { time: "10:00 pm", value: 0 },
              { time: "11:00 pm", value: 0 },
              { time: "12:00 pm", value: 0 },
            ],
            [
              { time: "1:00 AM", value: 3 },
              { time: "2:00 AM", value: 3 },
              { time: "3:00 AM", value: 3 },
              { time: "4:00 AM", value: 3 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 0 },
              { time: "7:00 AM", value: 0 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 0 },
              { time: "10:00 AM", value: 0 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 0 },
              { time: "1:00 pm", value: 1 },
              { time: "2:00 pm", value: 1 },
              { time: "3:00 pm", value: 1 },
              { time: "4:00 pm", value: 0 },
              { time: "5:00 pm", value: 0 },
              { time: "6:00 pm", value: 0 },
              { time: "7:00 pm", value: 3 },
              { time: "8:00 pm", value: 3 },
              { time: "9:00 pm", value: 3 },
              { time: "10:00 pm", value: 0 },
              { time: "11:00 pm", value: 0 },
              { time: "12:00 pm", value: 0 },
            ],
            [
              { time: "1:00 AM", value: 0 },
              { time: "2:00 AM", value: 0 },
              { time: "3:00 AM", value: 0 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 0 },
              { time: "7:00 AM", value: 0 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 0 },
              { time: "10:00 AM", value: 0 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 0 },
              { time: "1:00 pm", value: 0 },
              { time: "2:00 pm", value: 0 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 0 },
              { time: "5:00 pm", value: 0 },
              { time: "6:00 pm", value: 0 },
              { time: "7:00 pm", value: 0 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 0 },
              { time: "10:00 pm", value: 0 },
              { time: "11:00 pm", value: 0 },
              { time: "12:00 pm", value: 0 },
            ],
            [
              { time: "1:00 AM", value: 0 },
              { time: "2:00 AM", value: 0 },
              { time: "3:00 AM", value: 0 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 0 },
              { time: "7:00 AM", value: 0 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 0 },
              { time: "10:00 AM", value: 0 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 0 },
              { time: "1:00 pm", value: 0 },
              { time: "2:00 pm", value: 0 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 0 },
              { time: "5:00 pm", value: 0 },
              { time: "6:00 pm", value: 0 },
              { time: "7:00 pm", value: 0 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 0 },
              { time: "10:00 pm", value: 0 },
              { time: "11:00 pm", value: 0 },
              { time: "12:00 pm", value: 0 },
            ],
            [
              { time: "1:00 AM", value: 0 },
              { time: "2:00 AM", value: 0 },
              { time: "3:00 AM", value: 0 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 0 },
              { time: "7:00 AM", value: 0 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 0 },
              { time: "10:00 AM", value: 0 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 0 },
              { time: "1:00 pm", value: 0 },
              { time: "2:00 pm", value: 0 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 0 },
              { time: "5:00 pm", value: 0 },
              { time: "6:00 pm", value: 0 },
              { time: "7:00 pm", value: 0 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 0 },
              { time: "10:00 pm", value: 0 },
              { time: "11:00 pm", value: 0 },
              { time: "12:00 pm", value: 0 },
            ],
          ],
        };

      case 6:
        return {
          label: ["Label", "W", "T", "F", "S", "S", "M", "T"],
          data: [
            [
              { time: "1:00 AM", value: 2 },
              { time: "2:00 AM", value: 1 },
              { time: "3:00 AM", value: 1 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 4 },
              { time: "7:00 AM", value: 1 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 2 },
              { time: "10:00 AM", value: 5 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 1 },
              { time: "1:00 pm", value: 1 },
              { time: "2:00 pm", value: 2 },
              { time: "3:00 pm", value: 5 },
              { time: "4:00 pm", value: 5 },
              { time: "5:00 pm", value: 2 },
              { time: "6:00 pm", value: 2 },
              { time: "7:00 pm", value: 2 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 5 },
              { time: "10:00 pm", value: 4 },
              { time: "11:00 pm", value: 2 },
              { time: "12:00 pm", value: 0 },
            ],
            [
              { time: "1:00 AM", value: 0 },
              { time: "2:00 AM", value: 0 },
              { time: "3:00 AM", value: 0 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 0 },
              { time: "7:00 AM", value: 0 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 0 },
              { time: "10:00 AM", value: 0 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 0 },
              { time: "1:00 pm", value: 0 },
              { time: "2:00 pm", value: 0 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 0 },
              { time: "5:00 pm", value: 0 },
              { time: "6:00 pm", value: 0 },
              { time: "7:00 pm", value: 0 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 0 },
              { time: "10:00 pm", value: 0 },
              { time: "11:00 pm", value: 0 },
              { time: "12:00 pm", value: 0 },
            ],
            [
              { time: "1:00 AM", value: 0 },
              { time: "2:00 AM", value: 0 },
              { time: "3:00 AM", value: 0 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 0 },
              { time: "7:00 AM", value: 0 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 0 },
              { time: "10:00 AM", value: 0 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 0 },
              { time: "1:00 pm", value: 0 },
              { time: "2:00 pm", value: 0 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 0 },
              { time: "5:00 pm", value: 0 },
              { time: "6:00 pm", value: 0 },
              { time: "7:00 pm", value: 0 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 0 },
              { time: "10:00 pm", value: 0 },
              { time: "11:00 pm", value: 0 },
              { time: "12:00 pm", value: 0 },
            ],
            [
              { time: "1:00 AM", value: 0 },
              { time: "2:00 AM", value: 0 },
              { time: "3:00 AM", value: 0 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 0 },
              { time: "7:00 AM", value: 0 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 0 },
              { time: "10:00 AM", value: 0 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 0 },
              { time: "1:00 pm", value: 0 },
              { time: "2:00 pm", value: 0 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 0 },
              { time: "5:00 pm", value: 0 },
              { time: "6:00 pm", value: 0 },
              { time: "7:00 pm", value: 0 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 0 },
              { time: "10:00 pm", value: 0 },
              { time: "11:00 pm", value: 0 },
              { time: "12:00 pm", value: 0 },
            ],
            [
              { time: "1:00 AM", value: 0 },
              { time: "2:00 AM", value: 0 },
              { time: "3:00 AM", value: 1 },
              { time: "4:00 AM", value: 1 },
              { time: "5:00 AM", value: 1 },
              { time: "6:00 AM", value: 1 },
              { time: "7:00 AM", value: 1 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 0 },
              { time: "10:00 AM", value: 0 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 5 },
              { time: "1:00 pm", value: 5 },
              { time: "2:00 pm", value: 5 },
              { time: "3:00 pm", value: 5 },
              { time: "4:00 pm", value: 5 },
              { time: "5:00 pm", value: 0 },
              { time: "6:00 pm", value: 0 },
              { time: "7:00 pm", value: 0 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 5 },
              { time: "10:00 pm", value: 5 },
              { time: "11:00 pm", value: 5 },
              { time: "12:00 pm", value: 5 },
            ],
            [
              { time: "1:00 AM", value: 0 },
              { time: "2:00 AM", value: 0 },
              { time: "3:00 AM", value: 0 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 0 },
              { time: "7:00 AM", value: 0 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 0 },
              { time: "10:00 AM", value: 0 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 0 },
              { time: "1:00 pm", value: 0 },
              { time: "2:00 pm", value: 0 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 0 },
              { time: "5:00 pm", value: 0 },
              { time: "6:00 pm", value: 0 },
              { time: "7:00 pm", value: 0 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 0 },
              { time: "10:00 pm", value: 0 },
              { time: "11:00 pm", value: 0 },
              { time: "12:00 pm", value: 0 },
            ],
            [
              { time: "1:00 AM", value: 0 },
              { time: "2:00 AM", value: 0 },
              { time: "3:00 AM", value: 0 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 0 },
              { time: "7:00 AM", value: 0 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 0 },
              { time: "10:00 AM", value: 0 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 0 },
              { time: "1:00 pm", value: 0 },
              { time: "2:00 pm", value: 0 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 0 },
              { time: "5:00 pm", value: 0 },
              { time: "6:00 pm", value: 0 },
              { time: "7:00 pm", value: 0 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 0 },
              { time: "10:00 pm", value: 0 },
              { time: "11:00 pm", value: 0 },
              { time: "12:00 pm", value: 0 },
            ],
            [
              { time: "1:00 AM", value: 0 },
              { time: "2:00 AM", value: 0 },
              { time: "3:00 AM", value: 0 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 0 },
              { time: "7:00 AM", value: 0 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 0 },
              { time: "10:00 AM", value: 0 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 0 },
              { time: "1:00 pm", value: 0 },
              { time: "2:00 pm", value: 0 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 0 },
              { time: "5:00 pm", value: 0 },
              { time: "6:00 pm", value: 0 },
              { time: "7:00 pm", value: 0 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 0 },
              { time: "10:00 pm", value: 0 },
              { time: "11:00 pm", value: 0 },
              { time: "12:00 pm", value: 0 },
            ],
          ],
        };

      case 7:
        return {
          label: ["Label", "T", "F", "S", "S", "M", "T", "W"],
          data: [
            [
              { time: "1:00 AM", value: 2 },
              { time: "2:00 AM", value: 1 },
              { time: "3:00 AM", value: 1 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 4 },
              { time: "7:00 AM", value: 1 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 2 },
              { time: "10:00 AM", value: 5 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 1 },
              { time: "1:00 pm", value: 1 },
              { time: "2:00 pm", value: 2 },
              { time: "3:00 pm", value: 5 },
              { time: "4:00 pm", value: 5 },
              { time: "5:00 pm", value: 2 },
              { time: "6:00 pm", value: 2 },
              { time: "7:00 pm", value: 2 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 5 },
              { time: "10:00 pm", value: 4 },
              { time: "11:00 pm", value: 2 },
              { time: "12:00 pm", value: 0 },
            ],
            [
              { time: "1:00 AM", value: 0 },
              { time: "2:00 AM", value: 0 },
              { time: "3:00 AM", value: 0 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 0 },
              { time: "7:00 AM", value: 0 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 0 },
              { time: "10:00 AM", value: 0 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 0 },
              { time: "1:00 pm", value: 0 },
              { time: "2:00 pm", value: 0 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 0 },
              { time: "5:00 pm", value: 0 },
              { time: "6:00 pm", value: 0 },
              { time: "7:00 pm", value: 0 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 0 },
              { time: "10:00 pm", value: 0 },
              { time: "11:00 pm", value: 0 },
              { time: "12:00 pm", value: 0 },
            ],
            [
              { time: "1:00 AM", value: 0 },
              { time: "2:00 AM", value: 0 },
              { time: "3:00 AM", value: 0 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 0 },
              { time: "7:00 AM", value: 0 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 0 },
              { time: "10:00 AM", value: 0 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 0 },
              { time: "1:00 pm", value: 0 },
              { time: "2:00 pm", value: 0 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 0 },
              { time: "5:00 pm", value: 0 },
              { time: "6:00 pm", value: 0 },
              { time: "7:00 pm", value: 0 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 0 },
              { time: "10:00 pm", value: 0 },
              { time: "11:00 pm", value: 0 },
              { time: "12:00 pm", value: 0 },
            ],
            [
              { time: "1:00 AM", value: 0 },
              { time: "2:00 AM", value: 0 },
              { time: "3:00 AM", value: 0 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 0 },
              { time: "7:00 AM", value: 0 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 0 },
              { time: "10:00 AM", value: 0 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 0 },
              { time: "1:00 pm", value: 0 },
              { time: "2:00 pm", value: 0 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 0 },
              { time: "5:00 pm", value: 0 },
              { time: "6:00 pm", value: 0 },
              { time: "7:00 pm", value: 0 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 0 },
              { time: "10:00 pm", value: 0 },
              { time: "11:00 pm", value: 0 },
              { time: "12:00 pm", value: 0 },
            ],
            [
              { time: "1:00 AM", value: 0 },
              { time: "2:00 AM", value: 0 },
              { time: "3:00 AM", value: 0 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 2 },
              { time: "6:00 AM", value: 2 },
              { time: "7:00 AM", value: 2 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 0 },
              { time: "10:00 AM", value: 0 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 3 },
              { time: "1:00 pm", value: 3 },
              { time: "2:00 pm", value: 3 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 0 },
              { time: "5:00 pm", value: 0 },
              { time: "6:00 pm", value: 0 },
              { time: "7:00 pm", value: 0 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 3 },
              { time: "10:00 pm", value: 3 },
              { time: "11:00 pm", value: 3 },
              { time: "12:00 pm", value: 3 },
            ],
            [
              { time: "1:00 AM", value: 0 },
              { time: "2:00 AM", value: 0 },
              { time: "3:00 AM", value: 0 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 0 },
              { time: "7:00 AM", value: 0 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 0 },
              { time: "10:00 AM", value: 0 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 0 },
              { time: "1:00 pm", value: 0 },
              { time: "2:00 pm", value: 0 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 0 },
              { time: "5:00 pm", value: 0 },
              { time: "6:00 pm", value: 0 },
              { time: "7:00 pm", value: 0 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 0 },
              { time: "10:00 pm", value: 0 },
              { time: "11:00 pm", value: 0 },
              { time: "12:00 pm", value: 0 },
            ],
            [
              { time: "1:00 AM", value: 0 },
              { time: "2:00 AM", value: 0 },
              { time: "3:00 AM", value: 0 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 0 },
              { time: "7:00 AM", value: 0 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 0 },
              { time: "10:00 AM", value: 0 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 0 },
              { time: "1:00 pm", value: 0 },
              { time: "2:00 pm", value: 0 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 0 },
              { time: "5:00 pm", value: 0 },
              { time: "6:00 pm", value: 0 },
              { time: "7:00 pm", value: 0 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 0 },
              { time: "10:00 pm", value: 0 },
              { time: "11:00 pm", value: 0 },
              { time: "12:00 pm", value: 0 },
            ],
            [
              { time: "1:00 AM", value: 0 },
              { time: "2:00 AM", value: 0 },
              { time: "3:00 AM", value: 0 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 0 },
              { time: "7:00 AM", value: 0 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 0 },
              { time: "10:00 AM", value: 0 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 0 },
              { time: "1:00 pm", value: 0 },
              { time: "2:00 pm", value: 0 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 0 },
              { time: "5:00 pm", value: 0 },
              { time: "6:00 pm", value: 0 },
              { time: "7:00 pm", value: 0 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 0 },
              { time: "10:00 pm", value: 0 },
              { time: "11:00 pm", value: 0 },
              { time: "12:00 pm", value: 0 },
            ],
          ],
        };
      default:
        return {
          label: ["Label", "F", "S", "S", "M", "T", "W", "T"],
          data: [
            [
              { time: "1:00 AM", value: 2 },
              { time: "2:00 AM", value: 1 },
              { time: "3:00 AM", value: 1 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 4 },
              { time: "7:00 AM", value: 1 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 2 },
              { time: "10:00 AM", value: 5 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 1 },
              { time: "1:00 pm", value: 1 },
              { time: "2:00 pm", value: 2 },
              { time: "3:00 pm", value: 5 },
              { time: "4:00 pm", value: 5 },
              { time: "5:00 pm", value: 2 },
              { time: "6:00 pm", value: 2 },
              { time: "7:00 pm", value: 2 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 5 },
              { time: "10:00 pm", value: 4 },
              { time: "11:00 pm", value: 2 },
              { time: "12:00 pm", value: 0 },
            ],
            [
              { time: "1:00 AM", value: 2 },
              { time: "2:00 AM", value: 1 },
              { time: "3:00 AM", value: 1 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 0 },
              { time: "6:00 AM", value: 4 },
              { time: "7:00 AM", value: 1 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 2 },
              { time: "10:00 AM", value: 5 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 1 },
              { time: "1:00 pm", value: 1 },
              { time: "2:00 pm", value: 2 },
              { time: "3:00 pm", value: 5 },
              { time: "4:00 pm", value: 5 },
              { time: "5:00 pm", value: 2 },
              { time: "6:00 pm", value: 2 },
              { time: "7:00 pm", value: 2 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 5 },
              { time: "10:00 pm", value: 4 },
              { time: "11:00 pm", value: 2 },
              { time: "12:00 pm", value: 0 },
            ],
            [
              { time: "1:00 AM", value: 2 },
              { time: "2:00 AM", value: 1 },
              { time: "3:00 AM", value: 1 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 1 },
              { time: "6:00 AM", value: 0 },
              { time: "7:00 AM", value: 1 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 4 },
              { time: "10:00 AM", value: 5 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 1 },
              { time: "1:00 pm", value: 1 },
              { time: "2:00 pm", value: 2 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 5 },
              { time: "5:00 pm", value: 2 },
              { time: "6:00 pm", value: 1 },
              { time: "7:00 pm", value: 2 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 0 },
              { time: "10:00 pm", value: 4 },
              { time: "11:00 pm", value: 2 },
              { time: "12:00 pm", value: 0 },
            ],
            [
              { time: "1:00 AM", value: 2 },
              { time: "2:00 AM", value: 1 },
              { time: "3:00 AM", value: 1 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 1 },
              { time: "6:00 AM", value: 4 },
              { time: "7:00 AM", value: 1 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 4 },
              { time: "10:00 AM", value: 5 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 2 },
              { time: "1:00 pm", value: 1 },
              { time: "2:00 pm", value: 2 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 2 },
              { time: "5:00 pm", value: 2 },
              { time: "6:00 pm", value: 4 },
              { time: "7:00 pm", value: 2 },
              { time: "8:00 pm", value: 5 },
              { time: "9:00 pm", value: 5 },
              { time: "10:00 pm", value: 4 },
              { time: "11:00 pm", value: 2 },
              { time: "12:00 pm", value: 0 },
            ],
            [
              { time: "1:00 AM", value: 5 },
              { time: "2:00 AM", value: 1 },
              { time: "3:00 AM", value: 1 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 1 },
              { time: "6:00 AM", value: 4 },
              { time: "7:00 AM", value: 1 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 4 },
              { time: "10:00 AM", value: 1 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 5 },
              { time: "1:00 pm", value: 1 },
              { time: "2:00 pm", value: 2 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 5 },
              { time: "5:00 pm", value: 2 },
              { time: "6:00 pm", value: 1 },
              { time: "7:00 pm", value: 2 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 5 },
              { time: "10:00 pm", value: 4 },
              { time: "11:00 pm", value: 2 },
              { time: "12:00 pm", value: 5 },
            ],
            [
              { time: "1:00 AM", value: 2 },
              { time: "2:00 AM", value: 1 },
              { time: "3:00 AM", value: 1 },
              { time: "4:00 AM", value: 0 },
              { time: "5:00 AM", value: 1 },
              { time: "6:00 AM", value: 1 },
              { time: "7:00 AM", value: 1 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 4 },
              { time: "10:00 AM", value: 4 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 0 },
              { time: "1:00 pm", value: 1 },
              { time: "2:00 pm", value: 2 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 5 },
              { time: "5:00 pm", value: 2 },
              { time: "6:00 pm", value: 4 },
              { time: "7:00 pm", value: 2 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 2 },
              { time: "10:00 pm", value: 4 },
              { time: "11:00 pm", value: 2 },
              { time: "12:00 pm", value: 0 },
            ],
            [
              { time: "1:00 AM", value: 2 },
              { time: "2:00 AM", value: 1 },
              { time: "3:00 AM", value: 1 },
              { time: "4:00 AM", value: 5 },
              { time: "5:00 AM", value: 1 },
              { time: "6:00 AM", value: 4 },
              { time: "7:00 AM", value: 2 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 4 },
              { time: "10:00 AM", value: 5 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 4 },
              { time: "1:00 pm", value: 4 },
              { time: "2:00 pm", value: 2 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 5 },
              { time: "5:00 pm", value: 2 },
              { time: "6:00 pm", value: 4 },
              { time: "7:00 pm", value: 2 },
              { time: "8:00 pm", value: 2 },
              { time: "9:00 pm", value: 5 },
              { time: "10:00 pm", value: 4 },
              { time: "11:00 pm", value: 2 },
              { time: "12:00 pm", value: 0 },
            ],
            [
              { time: "1:00 AM", value: 2 },
              { time: "2:00 AM", value: 1 },
              { time: "3:00 AM", value: 0 },
              { time: "4:00 AM", value: 5 },
              { time: "5:00 AM", value: 1 },
              { time: "6:00 AM", value: 4 },
              { time: "7:00 AM", value: 1 },
              { time: "8:00 AM", value: 0 },
              { time: "9:00 AM", value: 4 },
              { time: "10:00 AM", value: 5 },
              { time: "11:00 AM", value: 0 },
              { time: "12:00 AM", value: 0 },
              { time: "1:00 pm", value: 1 },
              { time: "2:00 pm", value: 2 },
              { time: "3:00 pm", value: 0 },
              { time: "4:00 pm", value: 5 },
              { time: "5:00 pm", value: 2 },
              { time: "6:00 pm", value: 4 },
              { time: "7:00 pm", value: 4 },
              { time: "8:00 pm", value: 0 },
              { time: "9:00 pm", value: 5 },
              { time: "10:00 pm", value: 2 },
              { time: "11:00 pm", value: 2 },
              { time: "12:00 pm", value: 0 },
            ],
          ],
        };
    }
  };

  const styleValue = (arg, i, ind, styles) => {
    if (i !== 0) {
      switch (arg[ind].value) {
        case 0:
          return styles.valueNone;
        case 1:
          return styles.valueOne;

        case 2:
          return styles.valueTwo;
        case 3:
          return styles.valueThree;
        case 4:
          return styles.valueFour;
        case 5:
          return styles.valueFive;
      }
    } else {
      return styles.valueLabel;
    }
  };

  return (
    <HomePage
      day={day}
      setDay={setDay}
      labelByDay={labelByDay}
      styleValue={styleValue}
      profileDetail={profileDetail}
      {...props}
    />
  );
};
