import React, { useState } from "react";
import HomePage from "./homepage";
import moment from "moment";
import { useDispatch, useSelector } from "react-redux";
import sampleBabyCryingData from "./babyCryingSampleData.json";

export default HomepageContainer = (props) => {
  const { token, profileDetail, reload, crying_data } = useSelector(
    (state) => ({
      token: state.token.token,
      profileDetail: state.profileDetail.profileDetail,
      reload: state.reload.reload,
      crying_data: state.crying_data.crying_data,
    })
  );

  // console.log(
  //   "🚀 ~ file: homepageContainer.js ~ line 8 ~ crying_data",
  //   crying_data
  // );

  var weekday = [
    "Sunday",
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
  ];
  const dayLabel = (day) => {
    switch (day) {
      case 0:
        return "S";
      case 1:
        return "M";
      case 2:
        return "T";
      case 3:
        return "W";
      case 4:
        return "T";
      case 5:
        return "F";
      case 6:
        return "S";
    }
  };

  // console.log("asd", dayLabel(new Date(crying_data[0].date).getDay()));

  const weeklyData = [
    [
      { startTime: "1:00 AM" },
      { startTime: "2:00 AM" },
      { startTime: "3:00 AM" },
      { startTime: "4:00 AM" },
      { startTime: "5:00 AM" },
      { startTime: "6:00 AM" },
      { startTime: "7:00 AM" },
      { startTime: "8:00 AM" },
      { startTime: "9:00 AM" },
      { startTime: "10:00 AM" },
      { startTime: "11:00 AM" },
      { startTime: "12:00 AM" },
      { startTime: "1:00 pm" },
      { startTime: "2:00 pm" },
      { startTime: "3:00 pm" },
      { startTime: "4:00 pm" },
      { startTime: "5:00 pm" },
      { startTime: "6:00 pm" },
      { startTime: "7:00 pm" },
      { startTime: "8:00 pm" },
      { startTime: "9:00 pm" },
      { startTime: "10:00 pm" },
      { startTime: "11:00 pm" },
      { startTime: "12:00 pm" },
    ],
  ];
  // console.log(
  //   "🚀 ~ file: homepageContainer.js ~ line 84 ~ crying_data",
  //   crying_data
  // );
  crying_data.map((arg) => weeklyData.push(arg.baby_data));
  const serverData = {
    label: [
      "Label",
      dayLabel(new Date(crying_data[0]?.date).getDay()),
      dayLabel(new Date(crying_data[1]?.date).getDay()),
      dayLabel(new Date(crying_data[2]?.date).getDay()),
      dayLabel(new Date(crying_data[3]?.date).getDay()),
      dayLabel(new Date(crying_data[4]?.date).getDay()),
      dayLabel(new Date(crying_data[5]?.date).getDay()),
      dayLabel(new Date(crying_data[6]?.date).getDay()),
    ],
    data: weeklyData,
  };
  // console.log(
  //   "🚀 ~ file: homepageContainer.js ~ line 21 ~ serverData",
  //   serverData
  // );
  const [day, setDay] = useState("3");

  const labelByDay = (today) => {
    switch (today) {
      case 1:
        return {
          label: ["Label", "F", "S", "S", "M", "T", "W", "T"],
          data: [
            [
              { startTime: "1:00 AM", intensity: 2 },
              { startTime: "2:00 AM", intensity: 1 },
              { startTime: "3:00 AM", intensity: 1 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 4 },
              { startTime: "7:00 AM", intensity: 1 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 2 },
              { startTime: "10:00 AM", intensity: 5 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 1 },
              { startTime: "1:00 pm", intensity: 1 },
              { startTime: "2:00 pm", intensity: 2 },
              { startTime: "3:00 pm", intensity: 5 },
              { startTime: "4:00 pm", intensity: 5 },
              { startTime: "5:00 pm", intensity: 2 },
              { startTime: "6:00 pm", intensity: 2 },
              { startTime: "7:00 pm", intensity: 2 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 5 },
              { startTime: "10:00 pm", intensity: 4 },
              { startTime: "11:00 pm", intensity: 2 },
              { startTime: "12:00 pm", intensity: 0 },
            ],
            [
              { startTime: "1:00 AM", intensity: 0 },
              { startTime: "2:00 AM", intensity: 0 },
              { startTime: "3:00 AM", intensity: 0 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 0 },
              { startTime: "7:00 AM", intensity: 0 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 0 },
              { startTime: "10:00 AM", intensity: 0 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 0 },
              { startTime: "1:00 pm", intensity: 0 },
              { startTime: "2:00 pm", intensity: 0 },
              { startTime: "3:00 pm", intensity: 0 },
              { startTime: "4:00 pm", intensity: 0 },
              { startTime: "5:00 pm", intensity: 0 },
              { startTime: "6:00 pm", intensity: 0 },
              { startTime: "7:00 pm", intensity: 0 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 0 },
              { startTime: "10:00 pm", intensity: 0 },
              { startTime: "11:00 pm", intensity: 0 },
              { startTime: "12:00 pm", intensity: 0 },
            ],
            [
              { startTime: "1:00 AM", intensity: 0 },
              { startTime: "2:00 AM", intensity: 0 },
              { startTime: "3:00 AM", intensity: 0 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 0 },
              { startTime: "7:00 AM", intensity: 0 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 0 },
              { startTime: "10:00 AM", intensity: 0 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 0 },
              { startTime: "1:00 pm", intensity: 0 },
              { startTime: "2:00 pm", intensity: 0 },
              { startTime: "3:00 pm", intensity: 0 },
              { startTime: "4:00 pm", intensity: 0 },
              { startTime: "5:00 pm", intensity: 0 },
              { startTime: "6:00 pm", intensity: 0 },
              { startTime: "7:00 pm", intensity: 0 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 0 },
              { startTime: "10:00 pm", intensity: 0 },
              { startTime: "11:00 pm", intensity: 0 },
              { startTime: "12:00 pm", intensity: 0 },
            ],
            [
              { startTime: "1:00 AM", intensity: 0 },
              { startTime: "2:00 AM", intensity: 0 },
              { startTime: "3:00 AM", intensity: 0 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 0 },
              { startTime: "7:00 AM", intensity: 0 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 0 },
              { startTime: "10:00 AM", intensity: 0 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 0 },
              { startTime: "1:00 pm", intensity: 0 },
              { startTime: "2:00 pm", intensity: 0 },
              { startTime: "3:00 pm", intensity: 0 },
              { startTime: "4:00 pm", intensity: 0 },
              { startTime: "5:00 pm", intensity: 0 },
              { startTime: "6:00 pm", intensity: 0 },
              { startTime: "7:00 pm", intensity: 0 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 0 },
              { startTime: "10:00 pm", intensity: 0 },
              { startTime: "11:00 pm", intensity: 0 },
              { startTime: "12:00 pm", intensity: 0 },
            ],
            [
              { startTime: "1:00 AM", intensity: 0 },
              { startTime: "2:00 AM", intensity: 0 },
              { startTime: "3:00 AM", intensity: 0 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 3 },
              { startTime: "7:00 AM", intensity: 3 },
              { startTime: "8:00 AM", intensity: 3 },
              { startTime: "9:00 AM", intensity: 3 },
              { startTime: "10:00 AM", intensity: 3 },
              { startTime: "11:00 AM", intensity: 3 },
              { startTime: "12:00 AM", intensity: 3 },
              { startTime: "1:00 pm", intensity: 0 },
              { startTime: "2:00 pm", intensity: 0 },
              { startTime: "3:00 pm", intensity: 0 },
              { startTime: "4:00 pm", intensity: 0 },
              { startTime: "5:00 pm", intensity: 0 },
              { startTime: "6:00 pm", intensity: 0 },
              { startTime: "7:00 pm", intensity: 0 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 5 },
              { startTime: "10:00 pm", intensity: 5 },
              { startTime: "11:00 pm", intensity: 5 },
              { startTime: "12:00 pm", intensity: 5 },
            ],
            [
              { startTime: "1:00 AM", intensity: 0 },
              { startTime: "2:00 AM", intensity: 0 },
              { startTime: "3:00 AM", intensity: 0 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 0 },
              { startTime: "7:00 AM", intensity: 0 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 0 },
              { startTime: "10:00 AM", intensity: 0 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 0 },
              { startTime: "1:00 pm", intensity: 0 },
              { startTime: "2:00 pm", intensity: 0 },
              { startTime: "3:00 pm", intensity: 0 },
              { startTime: "4:00 pm", intensity: 0 },
              { startTime: "5:00 pm", intensity: 0 },
              { startTime: "6:00 pm", intensity: 0 },
              { startTime: "7:00 pm", intensity: 0 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 0 },
              { startTime: "10:00 pm", intensity: 0 },
              { startTime: "11:00 pm", intensity: 0 },
              { startTime: "12:00 pm", intensity: 0 },
            ],
            [
              { startTime: "1:00 AM", intensity: 0 },
              { startTime: "2:00 AM", intensity: 0 },
              { startTime: "3:00 AM", intensity: 0 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 0 },
              { startTime: "7:00 AM", intensity: 0 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 0 },
              { startTime: "10:00 AM", intensity: 0 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 0 },
              { startTime: "1:00 pm", intensity: 0 },
              { startTime: "2:00 pm", intensity: 0 },
              { startTime: "3:00 pm", intensity: 0 },
              { startTime: "4:00 pm", intensity: 0 },
              { startTime: "5:00 pm", intensity: 0 },
              { startTime: "6:00 pm", intensity: 0 },
              { startTime: "7:00 pm", intensity: 0 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 0 },
              { startTime: "10:00 pm", intensity: 0 },
              { startTime: "11:00 pm", intensity: 0 },
              { startTime: "12:00 pm", intensity: 0 },
            ],
            [
              { startTime: "1:00 AM", intensity: 0 },
              { startTime: "2:00 AM", intensity: 0 },
              { startTime: "3:00 AM", intensity: 0 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 0 },
              { startTime: "7:00 AM", intensity: 0 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 0 },
              { startTime: "10:00 AM", intensity: 0 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 0 },
              { startTime: "1:00 pm", intensity: 0 },
              { startTime: "2:00 pm", intensity: 0 },
              { startTime: "3:00 pm", intensity: 0 },
              { startTime: "4:00 pm", intensity: 0 },
              { startTime: "5:00 pm", intensity: 0 },
              { startTime: "6:00 pm", intensity: 0 },
              { startTime: "7:00 pm", intensity: 0 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 0 },
              { startTime: "10:00 pm", intensity: 0 },
              { startTime: "11:00 pm", intensity: 0 },
              { startTime: "12:00 pm", intensity: 0 },
            ],
          ],
        };
      case 2:
        return {
          label: ["Label", "S", "S", "M", "T", "W", "T", "F"],
          data: [
            [
              { startTime: "1:00 AM", intensity: 2 },
              { startTime: "2:00 AM", intensity: 1 },
              { startTime: "3:00 AM", intensity: 1 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 4 },
              { startTime: "7:00 AM", intensity: 1 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 2 },
              { startTime: "10:00 AM", intensity: 5 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 1 },
              { startTime: "1:00 pm", intensity: 1 },
              { startTime: "2:00 pm", intensity: 2 },
              { startTime: "3:00 pm", intensity: 5 },
              { startTime: "4:00 pm", intensity: 5 },
              { startTime: "5:00 pm", intensity: 2 },
              { startTime: "6:00 pm", intensity: 2 },
              { startTime: "7:00 pm", intensity: 2 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 5 },
              { startTime: "10:00 pm", intensity: 4 },
              { startTime: "11:00 pm", intensity: 2 },
              { startTime: "12:00 pm", intensity: 0 },
            ],
            [
              { startTime: "1:00 AM", intensity: 0 },
              { startTime: "2:00 AM", intensity: 0 },
              { startTime: "3:00 AM", intensity: 0 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 0 },
              { startTime: "7:00 AM", intensity: 0 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 0 },
              { startTime: "10:00 AM", intensity: 0 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 0 },
              { startTime: "1:00 pm", intensity: 0 },
              { startTime: "2:00 pm", intensity: 0 },
              { startTime: "3:00 pm", intensity: 0 },
              { startTime: "4:00 pm", intensity: 0 },
              { startTime: "5:00 pm", intensity: 0 },
              { startTime: "6:00 pm", intensity: 0 },
              { startTime: "7:00 pm", intensity: 0 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 0 },
              { startTime: "10:00 pm", intensity: 0 },
              { startTime: "11:00 pm", intensity: 0 },
              { startTime: "12:00 pm", intensity: 0 },
            ],
            [
              { startTime: "1:00 AM", intensity: 0 },
              { startTime: "2:00 AM", intensity: 0 },
              { startTime: "3:00 AM", intensity: 0 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 0 },
              { startTime: "7:00 AM", intensity: 0 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 0 },
              { startTime: "10:00 AM", intensity: 0 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 0 },
              { startTime: "1:00 pm", intensity: 0 },
              { startTime: "2:00 pm", intensity: 0 },
              { startTime: "3:00 pm", intensity: 0 },
              { startTime: "4:00 pm", intensity: 0 },
              { startTime: "5:00 pm", intensity: 0 },
              { startTime: "6:00 pm", intensity: 0 },
              { startTime: "7:00 pm", intensity: 0 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 0 },
              { startTime: "10:00 pm", intensity: 0 },
              { startTime: "11:00 pm", intensity: 0 },
              { startTime: "12:00 pm", intensity: 0 },
            ],
            [
              { startTime: "1:00 AM", intensity: 0 },
              { startTime: "2:00 AM", intensity: 0 },
              { startTime: "3:00 AM", intensity: 0 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 0 },
              { startTime: "7:00 AM", intensity: 0 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 0 },
              { startTime: "10:00 AM", intensity: 0 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 0 },
              { startTime: "1:00 pm", intensity: 0 },
              { startTime: "2:00 pm", intensity: 0 },
              { startTime: "3:00 pm", intensity: 0 },
              { startTime: "4:00 pm", intensity: 0 },
              { startTime: "5:00 pm", intensity: 0 },
              { startTime: "6:00 pm", intensity: 0 },
              { startTime: "7:00 pm", intensity: 0 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 0 },
              { startTime: "10:00 pm", intensity: 0 },
              { startTime: "11:00 pm", intensity: 0 },
              { startTime: "12:00 pm", intensity: 0 },
            ],
            [
              { startTime: "1:00 AM", intensity: 0 },
              { startTime: "2:00 AM", intensity: 0 },
              { startTime: "3:00 AM", intensity: 1 },
              { startTime: "4:00 AM", intensity: 1 },
              { startTime: "5:00 AM", intensity: 1 },
              { startTime: "6:00 AM", intensity: 1 },
              { startTime: "7:00 AM", intensity: 1 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 0 },
              { startTime: "10:00 AM", intensity: 0 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 4 },
              { startTime: "1:00 pm", intensity: 4 },
              { startTime: "2:00 pm", intensity: 4 },
              { startTime: "3:00 pm", intensity: 0 },
              { startTime: "4:00 pm", intensity: 0 },
              { startTime: "5:00 pm", intensity: 0 },
              { startTime: "6:00 pm", intensity: 0 },
              { startTime: "7:00 pm", intensity: 0 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 5 },
              { startTime: "10:00 pm", intensity: 5 },
              { startTime: "11:00 pm", intensity: 5 },
              { startTime: "12:00 pm", intensity: 5 },
            ],
            [
              { startTime: "1:00 AM", intensity: 0 },
              { startTime: "2:00 AM", intensity: 0 },
              { startTime: "3:00 AM", intensity: 0 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 0 },
              { startTime: "7:00 AM", intensity: 0 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 0 },
              { startTime: "10:00 AM", intensity: 0 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 0 },
              { startTime: "1:00 pm", intensity: 0 },
              { startTime: "2:00 pm", intensity: 0 },
              { startTime: "3:00 pm", intensity: 0 },
              { startTime: "4:00 pm", intensity: 0 },
              { startTime: "5:00 pm", intensity: 0 },
              { startTime: "6:00 pm", intensity: 0 },
              { startTime: "7:00 pm", intensity: 0 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 0 },
              { startTime: "10:00 pm", intensity: 0 },
              { startTime: "11:00 pm", intensity: 0 },
              { startTime: "12:00 pm", intensity: 0 },
            ],
            [
              { startTime: "1:00 AM", intensity: 0 },
              { startTime: "2:00 AM", intensity: 0 },
              { startTime: "3:00 AM", intensity: 0 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 0 },
              { startTime: "7:00 AM", intensity: 0 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 0 },
              { startTime: "10:00 AM", intensity: 0 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 0 },
              { startTime: "1:00 pm", intensity: 0 },
              { startTime: "2:00 pm", intensity: 0 },
              { startTime: "3:00 pm", intensity: 0 },
              { startTime: "4:00 pm", intensity: 0 },
              { startTime: "5:00 pm", intensity: 0 },
              { startTime: "6:00 pm", intensity: 0 },
              { startTime: "7:00 pm", intensity: 0 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 0 },
              { startTime: "10:00 pm", intensity: 0 },
              { startTime: "11:00 pm", intensity: 0 },
              { startTime: "12:00 pm", intensity: 0 },
            ],
            [
              { startTime: "1:00 AM", intensity: 0 },
              { startTime: "2:00 AM", intensity: 0 },
              { startTime: "3:00 AM", intensity: 0 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 0 },
              { startTime: "7:00 AM", intensity: 0 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 0 },
              { startTime: "10:00 AM", intensity: 0 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 0 },
              { startTime: "1:00 pm", intensity: 0 },
              { startTime: "2:00 pm", intensity: 0 },
              { startTime: "3:00 pm", intensity: 0 },
              { startTime: "4:00 pm", intensity: 0 },
              { startTime: "5:00 pm", intensity: 0 },
              { startTime: "6:00 pm", intensity: 0 },
              { startTime: "7:00 pm", intensity: 0 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 0 },
              { startTime: "10:00 pm", intensity: 0 },
              { startTime: "11:00 pm", intensity: 0 },
              { startTime: "12:00 pm", intensity: 0 },
            ],
          ],
        };

      case 3:
        return {
          label: ["Label", "S", "M", "W", "W", "T", "F", "S"],
          data: [
            [
              { startTime: "1:00 AM", intensity: 2 },
              { startTime: "2:00 AM", intensity: 1 },
              { startTime: "3:00 AM", intensity: 1 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 4 },
              { startTime: "7:00 AM", intensity: 1 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 2 },
              { startTime: "10:00 AM", intensity: 5 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 1 },
              { startTime: "1:00 pm", intensity: 1 },
              { startTime: "2:00 pm", intensity: 2 },
              { startTime: "3:00 pm", intensity: 5 },
              { startTime: "4:00 pm", intensity: 5 },
              { startTime: "5:00 pm", intensity: 2 },
              { startTime: "6:00 pm", intensity: 2 },
              { startTime: "7:00 pm", intensity: 2 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 5 },
              { startTime: "10:00 pm", intensity: 4 },
              { startTime: "11:00 pm", intensity: 2 },
              { startTime: "12:00 pm", intensity: 0 },
            ],
            [
              { startTime: "1:00 AM", intensity: 0 },
              { startTime: "2:00 AM", intensity: 0 },
              { startTime: "3:00 AM", intensity: 0 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 0 },
              { startTime: "7:00 AM", intensity: 0 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 0 },
              { startTime: "10:00 AM", intensity: 0 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 0 },
              { startTime: "1:00 pm", intensity: 0 },
              { startTime: "2:00 pm", intensity: 0 },
              { startTime: "3:00 pm", intensity: 0 },
              { startTime: "4:00 pm", intensity: 0 },
              { startTime: "5:00 pm", intensity: 0 },
              { startTime: "6:00 pm", intensity: 0 },
              { startTime: "7:00 pm", intensity: 0 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 0 },
              { startTime: "10:00 pm", intensity: 0 },
              { startTime: "11:00 pm", intensity: 0 },
              { startTime: "12:00 pm", intensity: 0 },
            ],
            [
              { startTime: "1:00 AM", intensity: 0 },
              { startTime: "2:00 AM", intensity: 0 },
              { startTime: "3:00 AM", intensity: 0 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 0 },
              { startTime: "7:00 AM", intensity: 0 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 0 },
              { startTime: "10:00 AM", intensity: 0 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 0 },
              { startTime: "1:00 pm", intensity: 0 },
              { startTime: "2:00 pm", intensity: 0 },
              { startTime: "3:00 pm", intensity: 0 },
              { startTime: "4:00 pm", intensity: 0 },
              { startTime: "5:00 pm", intensity: 0 },
              { startTime: "6:00 pm", intensity: 0 },
              { startTime: "7:00 pm", intensity: 0 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 0 },
              { startTime: "10:00 pm", intensity: 0 },
              { startTime: "11:00 pm", intensity: 0 },
              { startTime: "12:00 pm", intensity: 0 },
            ],
            [
              { startTime: "1:00 AM", intensity: 0 },
              { startTime: "2:00 AM", intensity: 0 },
              { startTime: "3:00 AM", intensity: 0 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 0 },
              { startTime: "7:00 AM", intensity: 0 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 0 },
              { startTime: "10:00 AM", intensity: 0 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 0 },
              { startTime: "1:00 pm", intensity: 0 },
              { startTime: "2:00 pm", intensity: 0 },
              { startTime: "3:00 pm", intensity: 0 },
              { startTime: "4:00 pm", intensity: 0 },
              { startTime: "5:00 pm", intensity: 0 },
              { startTime: "6:00 pm", intensity: 0 },
              { startTime: "7:00 pm", intensity: 0 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 0 },
              { startTime: "10:00 pm", intensity: 0 },
              { startTime: "11:00 pm", intensity: 0 },
              { startTime: "12:00 pm", intensity: 0 },
            ],
            [
              { startTime: "1:00 AM", intensity: 3 },
              { startTime: "2:00 AM", intensity: 3 },
              { startTime: "3:00 AM", intensity: 3 },
              { startTime: "4:00 AM", intensity: 3 },
              { startTime: "5:00 AM", intensity: 3 },
              { startTime: "6:00 AM", intensity: 3 },
              { startTime: "7:00 AM", intensity: 0 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 0 },
              { startTime: "10:00 AM", intensity: 0 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 0 },
              { startTime: "1:00 pm", intensity: 0 },
              { startTime: "2:00 pm", intensity: 0 },
              { startTime: "3:00 pm", intensity: 0 },
              { startTime: "4:00 pm", intensity: 0 },
              { startTime: "5:00 pm", intensity: 2 },
              { startTime: "6:00 pm", intensity: 2 },
              { startTime: "7:00 pm", intensity: 2 },
              { startTime: "8:00 pm", intensity: 2 },
              { startTime: "9:00 pm", intensity: 0 },
              { startTime: "10:00 pm", intensity: 0 },
              { startTime: "11:00 pm", intensity: 0 },
              { startTime: "12:00 pm", intensity: 0 },
            ],
            [
              { startTime: "1:00 AM", intensity: 0 },
              { startTime: "2:00 AM", intensity: 0 },
              { startTime: "3:00 AM", intensity: 0 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 0 },
              { startTime: "7:00 AM", intensity: 0 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 0 },
              { startTime: "10:00 AM", intensity: 0 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 0 },
              { startTime: "1:00 pm", intensity: 0 },
              { startTime: "2:00 pm", intensity: 0 },
              { startTime: "3:00 pm", intensity: 0 },
              { startTime: "4:00 pm", intensity: 0 },
              { startTime: "5:00 pm", intensity: 0 },
              { startTime: "6:00 pm", intensity: 0 },
              { startTime: "7:00 pm", intensity: 0 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 0 },
              { startTime: "10:00 pm", intensity: 0 },
              { startTime: "11:00 pm", intensity: 0 },
              { startTime: "12:00 pm", intensity: 0 },
            ],
            [
              { startTime: "1:00 AM", intensity: 0 },
              { startTime: "2:00 AM", intensity: 0 },
              { startTime: "3:00 AM", intensity: 0 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 0 },
              { startTime: "7:00 AM", intensity: 0 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 0 },
              { startTime: "10:00 AM", intensity: 0 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 0 },
              { startTime: "1:00 pm", intensity: 0 },
              { startTime: "2:00 pm", intensity: 0 },
              { startTime: "3:00 pm", intensity: 0 },
              { startTime: "4:00 pm", intensity: 0 },
              { startTime: "5:00 pm", intensity: 0 },
              { startTime: "6:00 pm", intensity: 0 },
              { startTime: "7:00 pm", intensity: 0 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 0 },
              { startTime: "10:00 pm", intensity: 0 },
              { startTime: "11:00 pm", intensity: 0 },
              { startTime: "12:00 pm", intensity: 0 },
            ],
            [
              { startTime: "1:00 AM", intensity: 0 },
              { startTime: "2:00 AM", intensity: 0 },
              { startTime: "3:00 AM", intensity: 0 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 0 },
              { startTime: "7:00 AM", intensity: 0 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 0 },
              { startTime: "10:00 AM", intensity: 0 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 0 },
              { startTime: "1:00 pm", intensity: 0 },
              { startTime: "2:00 pm", intensity: 0 },
              { startTime: "3:00 pm", intensity: 0 },
              { startTime: "4:00 pm", intensity: 0 },
              { startTime: "5:00 pm", intensity: 0 },
              { startTime: "6:00 pm", intensity: 0 },
              { startTime: "7:00 pm", intensity: 0 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 0 },
              { startTime: "10:00 pm", intensity: 0 },
              { startTime: "11:00 pm", intensity: 0 },
              { startTime: "12:00 pm", intensity: 0 },
            ],
          ],
        };

      case 4:
        return {
          label: ["Label", "M", "T", "W", "T", "F", "S", "S"],
          data: [
            [
              { startTime: "1:00 AM", intensity: 2 },
              { startTime: "2:00 AM", intensity: 1 },
              { startTime: "3:00 AM", intensity: 1 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 4 },
              { startTime: "7:00 AM", intensity: 1 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 2 },
              { startTime: "10:00 AM", intensity: 5 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 1 },
              { startTime: "1:00 pm", intensity: 1 },
              { startTime: "2:00 pm", intensity: 2 },
              { startTime: "3:00 pm", intensity: 5 },
              { startTime: "4:00 pm", intensity: 5 },
              { startTime: "5:00 pm", intensity: 2 },
              { startTime: "6:00 pm", intensity: 2 },
              { startTime: "7:00 pm", intensity: 2 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 5 },
              { startTime: "10:00 pm", intensity: 4 },
              { startTime: "11:00 pm", intensity: 2 },
              { startTime: "12:00 pm", intensity: 0 },
            ],
            [
              { startTime: "1:00 AM", intensity: 0 },
              { startTime: "2:00 AM", intensity: 0 },
              { startTime: "3:00 AM", intensity: 0 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 0 },
              { startTime: "7:00 AM", intensity: 0 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 0 },
              { startTime: "10:00 AM", intensity: 0 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 0 },
              { startTime: "1:00 pm", intensity: 0 },
              { startTime: "2:00 pm", intensity: 0 },
              { startTime: "3:00 pm", intensity: 0 },
              { startTime: "4:00 pm", intensity: 0 },
              { startTime: "5:00 pm", intensity: 0 },
              { startTime: "6:00 pm", intensity: 0 },
              { startTime: "7:00 pm", intensity: 0 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 0 },
              { startTime: "10:00 pm", intensity: 0 },
              { startTime: "11:00 pm", intensity: 0 },
              { startTime: "12:00 pm", intensity: 0 },
            ],
            [
              { startTime: "1:00 AM", intensity: 0 },
              { startTime: "2:00 AM", intensity: 0 },
              { startTime: "3:00 AM", intensity: 0 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 0 },
              { startTime: "7:00 AM", intensity: 0 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 0 },
              { startTime: "10:00 AM", intensity: 0 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 0 },
              { startTime: "1:00 pm", intensity: 0 },
              { startTime: "2:00 pm", intensity: 0 },
              { startTime: "3:00 pm", intensity: 0 },
              { startTime: "4:00 pm", intensity: 0 },
              { startTime: "5:00 pm", intensity: 0 },
              { startTime: "6:00 pm", intensity: 0 },
              { startTime: "7:00 pm", intensity: 0 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 0 },
              { startTime: "10:00 pm", intensity: 0 },
              { startTime: "11:00 pm", intensity: 0 },
              { startTime: "12:00 pm", intensity: 0 },
            ],
            [
              { startTime: "1:00 AM", intensity: 0 },
              { startTime: "2:00 AM", intensity: 0 },
              { startTime: "3:00 AM", intensity: 0 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 0 },
              { startTime: "7:00 AM", intensity: 0 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 0 },
              { startTime: "10:00 AM", intensity: 0 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 0 },
              { startTime: "1:00 pm", intensity: 0 },
              { startTime: "2:00 pm", intensity: 0 },
              { startTime: "3:00 pm", intensity: 0 },
              { startTime: "4:00 pm", intensity: 0 },
              { startTime: "5:00 pm", intensity: 0 },
              { startTime: "6:00 pm", intensity: 0 },
              { startTime: "7:00 pm", intensity: 0 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 0 },
              { startTime: "10:00 pm", intensity: 0 },
              { startTime: "11:00 pm", intensity: 0 },
              { startTime: "12:00 pm", intensity: 0 },
            ],
            [
              { startTime: "1:00 AM", intensity: 0 },
              { startTime: "2:00 AM", intensity: 0 },
              { startTime: "3:00 AM", intensity: 0 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 0 },
              { startTime: "7:00 AM", intensity: 0 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 0 },
              { startTime: "10:00 AM", intensity: 1 },
              { startTime: "11:00 AM", intensity: 1 },
              { startTime: "12:00 AM", intensity: 1 },
              { startTime: "1:00 pm", intensity: 1 },
              { startTime: "2:00 pm", intensity: 1 },
              { startTime: "3:00 pm", intensity: 0 },
              { startTime: "4:00 pm", intensity: 0 },
              { startTime: "5:00 pm", intensity: 0 },
              { startTime: "6:00 pm", intensity: 0 },
              { startTime: "7:00 pm", intensity: 0 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 5 },
              { startTime: "10:00 pm", intensity: 5 },
              { startTime: "11:00 pm", intensity: 5 },
              { startTime: "12:00 pm", intensity: 5 },
            ],
            [
              { startTime: "1:00 AM", intensity: 0 },
              { startTime: "2:00 AM", intensity: 0 },
              { startTime: "3:00 AM", intensity: 0 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 0 },
              { startTime: "7:00 AM", intensity: 0 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 0 },
              { startTime: "10:00 AM", intensity: 0 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 0 },
              { startTime: "1:00 pm", intensity: 0 },
              { startTime: "2:00 pm", intensity: 0 },
              { startTime: "3:00 pm", intensity: 0 },
              { startTime: "4:00 pm", intensity: 0 },
              { startTime: "5:00 pm", intensity: 0 },
              { startTime: "6:00 pm", intensity: 0 },
              { startTime: "7:00 pm", intensity: 0 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 0 },
              { startTime: "10:00 pm", intensity: 0 },
              { startTime: "11:00 pm", intensity: 0 },
              { startTime: "12:00 pm", intensity: 0 },
            ],
            [
              { startTime: "1:00 AM", intensity: 0 },
              { startTime: "2:00 AM", intensity: 0 },
              { startTime: "3:00 AM", intensity: 0 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 0 },
              { startTime: "7:00 AM", intensity: 0 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 0 },
              { startTime: "10:00 AM", intensity: 0 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 0 },
              { startTime: "1:00 pm", intensity: 0 },
              { startTime: "2:00 pm", intensity: 0 },
              { startTime: "3:00 pm", intensity: 0 },
              { startTime: "4:00 pm", intensity: 0 },
              { startTime: "5:00 pm", intensity: 0 },
              { startTime: "6:00 pm", intensity: 0 },
              { startTime: "7:00 pm", intensity: 0 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 0 },
              { startTime: "10:00 pm", intensity: 0 },
              { startTime: "11:00 pm", intensity: 0 },
              { startTime: "12:00 pm", intensity: 0 },
            ],
            [
              { startTime: "1:00 AM", intensity: 0 },
              { startTime: "2:00 AM", intensity: 0 },
              { startTime: "3:00 AM", intensity: 0 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 0 },
              { startTime: "7:00 AM", intensity: 0 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 0 },
              { startTime: "10:00 AM", intensity: 0 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 0 },
              { startTime: "1:00 pm", intensity: 0 },
              { startTime: "2:00 pm", intensity: 0 },
              { startTime: "3:00 pm", intensity: 0 },
              { startTime: "4:00 pm", intensity: 0 },
              { startTime: "5:00 pm", intensity: 0 },
              { startTime: "6:00 pm", intensity: 0 },
              { startTime: "7:00 pm", intensity: 0 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 0 },
              { startTime: "10:00 pm", intensity: 0 },
              { startTime: "11:00 pm", intensity: 0 },
              { startTime: "12:00 pm", intensity: 0 },
            ],
          ],
        };

      case 5:
        return {
          label: ["Label", "T", "W", "T", "F", "S", "S", "M"],
          data: [
            [
              { startTime: "1:00 AM", intensity: 2 },
              { startTime: "2:00 AM", intensity: 1 },
              { startTime: "3:00 AM", intensity: 1 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 4 },
              { startTime: "7:00 AM", intensity: 1 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 2 },
              { startTime: "10:00 AM", intensity: 5 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 1 },
              { startTime: "1:00 pm", intensity: 1 },
              { startTime: "2:00 pm", intensity: 2 },
              { startTime: "3:00 pm", intensity: 5 },
              { startTime: "4:00 pm", intensity: 5 },
              { startTime: "5:00 pm", intensity: 2 },
              { startTime: "6:00 pm", intensity: 2 },
              { startTime: "7:00 pm", intensity: 2 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 5 },
              { startTime: "10:00 pm", intensity: 4 },
              { startTime: "11:00 pm", intensity: 2 },
              { startTime: "12:00 pm", intensity: 0 },
            ],
            [
              { startTime: "1:00 AM", intensity: 0 },
              { startTime: "2:00 AM", intensity: 0 },
              { startTime: "3:00 AM", intensity: 0 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 0 },
              { startTime: "7:00 AM", intensity: 0 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 0 },
              { startTime: "10:00 AM", intensity: 0 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 0 },
              { startTime: "1:00 pm", intensity: 0 },
              { startTime: "2:00 pm", intensity: 0 },
              { startTime: "3:00 pm", intensity: 0 },
              { startTime: "4:00 pm", intensity: 0 },
              { startTime: "5:00 pm", intensity: 0 },
              { startTime: "6:00 pm", intensity: 0 },
              { startTime: "7:00 pm", intensity: 0 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 0 },
              { startTime: "10:00 pm", intensity: 0 },
              { startTime: "11:00 pm", intensity: 0 },
              { startTime: "12:00 pm", intensity: 0 },
            ],
            [
              { startTime: "1:00 AM", intensity: 0 },
              { startTime: "2:00 AM", intensity: 0 },
              { startTime: "3:00 AM", intensity: 0 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 0 },
              { startTime: "7:00 AM", intensity: 0 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 0 },
              { startTime: "10:00 AM", intensity: 0 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 0 },
              { startTime: "1:00 pm", intensity: 0 },
              { startTime: "2:00 pm", intensity: 0 },
              { startTime: "3:00 pm", intensity: 0 },
              { startTime: "4:00 pm", intensity: 0 },
              { startTime: "5:00 pm", intensity: 0 },
              { startTime: "6:00 pm", intensity: 0 },
              { startTime: "7:00 pm", intensity: 0 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 0 },
              { startTime: "10:00 pm", intensity: 0 },
              { startTime: "11:00 pm", intensity: 0 },
              { startTime: "12:00 pm", intensity: 0 },
            ],
            [
              { startTime: "1:00 AM", intensity: 0 },
              { startTime: "2:00 AM", intensity: 0 },
              { startTime: "3:00 AM", intensity: 0 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 0 },
              { startTime: "7:00 AM", intensity: 0 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 0 },
              { startTime: "10:00 AM", intensity: 0 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 0 },
              { startTime: "1:00 pm", intensity: 0 },
              { startTime: "2:00 pm", intensity: 0 },
              { startTime: "3:00 pm", intensity: 0 },
              { startTime: "4:00 pm", intensity: 0 },
              { startTime: "5:00 pm", intensity: 0 },
              { startTime: "6:00 pm", intensity: 0 },
              { startTime: "7:00 pm", intensity: 0 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 0 },
              { startTime: "10:00 pm", intensity: 0 },
              { startTime: "11:00 pm", intensity: 0 },
              { startTime: "12:00 pm", intensity: 0 },
            ],
            [
              { startTime: "1:00 AM", intensity: 3 },
              { startTime: "2:00 AM", intensity: 3 },
              { startTime: "3:00 AM", intensity: 3 },
              { startTime: "4:00 AM", intensity: 3 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 0 },
              { startTime: "7:00 AM", intensity: 0 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 0 },
              { startTime: "10:00 AM", intensity: 0 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 0 },
              { startTime: "1:00 pm", intensity: 1 },
              { startTime: "2:00 pm", intensity: 1 },
              { startTime: "3:00 pm", intensity: 1 },
              { startTime: "4:00 pm", intensity: 0 },
              { startTime: "5:00 pm", intensity: 0 },
              { startTime: "6:00 pm", intensity: 0 },
              { startTime: "7:00 pm", intensity: 3 },
              { startTime: "8:00 pm", intensity: 3 },
              { startTime: "9:00 pm", intensity: 3 },
              { startTime: "10:00 pm", intensity: 0 },
              { startTime: "11:00 pm", intensity: 0 },
              { startTime: "12:00 pm", intensity: 0 },
            ],
            [
              { startTime: "1:00 AM", intensity: 0 },
              { startTime: "2:00 AM", intensity: 0 },
              { startTime: "3:00 AM", intensity: 0 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 0 },
              { startTime: "7:00 AM", intensity: 0 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 0 },
              { startTime: "10:00 AM", intensity: 0 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 0 },
              { startTime: "1:00 pm", intensity: 0 },
              { startTime: "2:00 pm", intensity: 0 },
              { startTime: "3:00 pm", intensity: 0 },
              { startTime: "4:00 pm", intensity: 0 },
              { startTime: "5:00 pm", intensity: 0 },
              { startTime: "6:00 pm", intensity: 0 },
              { startTime: "7:00 pm", intensity: 0 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 0 },
              { startTime: "10:00 pm", intensity: 0 },
              { startTime: "11:00 pm", intensity: 0 },
              { startTime: "12:00 pm", intensity: 0 },
            ],
            [
              { startTime: "1:00 AM", intensity: 0 },
              { startTime: "2:00 AM", intensity: 0 },
              { startTime: "3:00 AM", intensity: 0 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 0 },
              { startTime: "7:00 AM", intensity: 0 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 0 },
              { startTime: "10:00 AM", intensity: 0 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 0 },
              { startTime: "1:00 pm", intensity: 0 },
              { startTime: "2:00 pm", intensity: 0 },
              { startTime: "3:00 pm", intensity: 0 },
              { startTime: "4:00 pm", intensity: 0 },
              { startTime: "5:00 pm", intensity: 0 },
              { startTime: "6:00 pm", intensity: 0 },
              { startTime: "7:00 pm", intensity: 0 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 0 },
              { startTime: "10:00 pm", intensity: 0 },
              { startTime: "11:00 pm", intensity: 0 },
              { startTime: "12:00 pm", intensity: 0 },
            ],
            [
              { startTime: "1:00 AM", intensity: 0 },
              { startTime: "2:00 AM", intensity: 0 },
              { startTime: "3:00 AM", intensity: 0 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 0 },
              { startTime: "7:00 AM", intensity: 0 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 0 },
              { startTime: "10:00 AM", intensity: 0 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 0 },
              { startTime: "1:00 pm", intensity: 0 },
              { startTime: "2:00 pm", intensity: 0 },
              { startTime: "3:00 pm", intensity: 0 },
              { startTime: "4:00 pm", intensity: 0 },
              { startTime: "5:00 pm", intensity: 0 },
              { startTime: "6:00 pm", intensity: 0 },
              { startTime: "7:00 pm", intensity: 0 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 0 },
              { startTime: "10:00 pm", intensity: 0 },
              { startTime: "11:00 pm", intensity: 0 },
              { startTime: "12:00 pm", intensity: 0 },
            ],
          ],
        };

      case 6:
        return {
          label: ["Label", "W", "T", "F", "S", "S", "M", "T"],
          data: [
            [
              { startTime: "1:00 AM", intensity: 2 },
              { startTime: "2:00 AM", intensity: 1 },
              { startTime: "3:00 AM", intensity: 1 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 4 },
              { startTime: "7:00 AM", intensity: 1 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 2 },
              { startTime: "10:00 AM", intensity: 5 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 1 },
              { startTime: "1:00 pm", intensity: 1 },
              { startTime: "2:00 pm", intensity: 2 },
              { startTime: "3:00 pm", intensity: 5 },
              { startTime: "4:00 pm", intensity: 5 },
              { startTime: "5:00 pm", intensity: 2 },
              { startTime: "6:00 pm", intensity: 2 },
              { startTime: "7:00 pm", intensity: 2 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 5 },
              { startTime: "10:00 pm", intensity: 4 },
              { startTime: "11:00 pm", intensity: 2 },
              { startTime: "12:00 pm", intensity: 0 },
            ],
            [
              { startTime: "1:00 AM", intensity: 0 },
              { startTime: "2:00 AM", intensity: 0 },
              { startTime: "3:00 AM", intensity: 0 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 0 },
              { startTime: "7:00 AM", intensity: 0 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 0 },
              { startTime: "10:00 AM", intensity: 0 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 0 },
              { startTime: "1:00 pm", intensity: 0 },
              { startTime: "2:00 pm", intensity: 0 },
              { startTime: "3:00 pm", intensity: 0 },
              { startTime: "4:00 pm", intensity: 0 },
              { startTime: "5:00 pm", intensity: 0 },
              { startTime: "6:00 pm", intensity: 0 },
              { startTime: "7:00 pm", intensity: 0 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 0 },
              { startTime: "10:00 pm", intensity: 0 },
              { startTime: "11:00 pm", intensity: 0 },
              { startTime: "12:00 pm", intensity: 0 },
            ],
            [
              { startTime: "1:00 AM", intensity: 0 },
              { startTime: "2:00 AM", intensity: 0 },
              { startTime: "3:00 AM", intensity: 0 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 0 },
              { startTime: "7:00 AM", intensity: 0 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 0 },
              { startTime: "10:00 AM", intensity: 0 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 0 },
              { startTime: "1:00 pm", intensity: 0 },
              { startTime: "2:00 pm", intensity: 0 },
              { startTime: "3:00 pm", intensity: 0 },
              { startTime: "4:00 pm", intensity: 0 },
              { startTime: "5:00 pm", intensity: 0 },
              { startTime: "6:00 pm", intensity: 0 },
              { startTime: "7:00 pm", intensity: 0 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 0 },
              { startTime: "10:00 pm", intensity: 0 },
              { startTime: "11:00 pm", intensity: 0 },
              { startTime: "12:00 pm", intensity: 0 },
            ],
            [
              { startTime: "1:00 AM", intensity: 0 },
              { startTime: "2:00 AM", intensity: 0 },
              { startTime: "3:00 AM", intensity: 0 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 0 },
              { startTime: "7:00 AM", intensity: 0 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 0 },
              { startTime: "10:00 AM", intensity: 0 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 0 },
              { startTime: "1:00 pm", intensity: 0 },
              { startTime: "2:00 pm", intensity: 0 },
              { startTime: "3:00 pm", intensity: 0 },
              { startTime: "4:00 pm", intensity: 0 },
              { startTime: "5:00 pm", intensity: 0 },
              { startTime: "6:00 pm", intensity: 0 },
              { startTime: "7:00 pm", intensity: 0 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 0 },
              { startTime: "10:00 pm", intensity: 0 },
              { startTime: "11:00 pm", intensity: 0 },
              { startTime: "12:00 pm", intensity: 0 },
            ],
            [
              { startTime: "1:00 AM", intensity: 0 },
              { startTime: "2:00 AM", intensity: 0 },
              { startTime: "3:00 AM", intensity: 1 },
              { startTime: "4:00 AM", intensity: 1 },
              { startTime: "5:00 AM", intensity: 1 },
              { startTime: "6:00 AM", intensity: 1 },
              { startTime: "7:00 AM", intensity: 1 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 0 },
              { startTime: "10:00 AM", intensity: 0 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 5 },
              { startTime: "1:00 pm", intensity: 5 },
              { startTime: "2:00 pm", intensity: 5 },
              { startTime: "3:00 pm", intensity: 5 },
              { startTime: "4:00 pm", intensity: 5 },
              { startTime: "5:00 pm", intensity: 0 },
              { startTime: "6:00 pm", intensity: 0 },
              { startTime: "7:00 pm", intensity: 0 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 5 },
              { startTime: "10:00 pm", intensity: 5 },
              { startTime: "11:00 pm", intensity: 5 },
              { startTime: "12:00 pm", intensity: 5 },
            ],
            [
              { startTime: "1:00 AM", intensity: 0 },
              { startTime: "2:00 AM", intensity: 0 },
              { startTime: "3:00 AM", intensity: 0 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 0 },
              { startTime: "7:00 AM", intensity: 0 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 0 },
              { startTime: "10:00 AM", intensity: 0 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 0 },
              { startTime: "1:00 pm", intensity: 0 },
              { startTime: "2:00 pm", intensity: 0 },
              { startTime: "3:00 pm", intensity: 0 },
              { startTime: "4:00 pm", intensity: 0 },
              { startTime: "5:00 pm", intensity: 0 },
              { startTime: "6:00 pm", intensity: 0 },
              { startTime: "7:00 pm", intensity: 0 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 0 },
              { startTime: "10:00 pm", intensity: 0 },
              { startTime: "11:00 pm", intensity: 0 },
              { startTime: "12:00 pm", intensity: 0 },
            ],
            [
              { startTime: "1:00 AM", intensity: 0 },
              { startTime: "2:00 AM", intensity: 0 },
              { startTime: "3:00 AM", intensity: 0 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 0 },
              { startTime: "7:00 AM", intensity: 0 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 0 },
              { startTime: "10:00 AM", intensity: 0 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 0 },
              { startTime: "1:00 pm", intensity: 0 },
              { startTime: "2:00 pm", intensity: 0 },
              { startTime: "3:00 pm", intensity: 0 },
              { startTime: "4:00 pm", intensity: 0 },
              { startTime: "5:00 pm", intensity: 0 },
              { startTime: "6:00 pm", intensity: 0 },
              { startTime: "7:00 pm", intensity: 0 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 0 },
              { startTime: "10:00 pm", intensity: 0 },
              { startTime: "11:00 pm", intensity: 0 },
              { startTime: "12:00 pm", intensity: 0 },
            ],
            [
              { startTime: "1:00 AM", intensity: 0 },
              { startTime: "2:00 AM", intensity: 0 },
              { startTime: "3:00 AM", intensity: 0 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 0 },
              { startTime: "7:00 AM", intensity: 0 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 0 },
              { startTime: "10:00 AM", intensity: 0 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 0 },
              { startTime: "1:00 pm", intensity: 0 },
              { startTime: "2:00 pm", intensity: 0 },
              { startTime: "3:00 pm", intensity: 0 },
              { startTime: "4:00 pm", intensity: 0 },
              { startTime: "5:00 pm", intensity: 0 },
              { startTime: "6:00 pm", intensity: 0 },
              { startTime: "7:00 pm", intensity: 0 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 0 },
              { startTime: "10:00 pm", intensity: 0 },
              { startTime: "11:00 pm", intensity: 0 },
              { startTime: "12:00 pm", intensity: 0 },
            ],
          ],
        };

      case 7:
        return {
          label: ["Label", "T", "F", "S", "S", "M", "T", "W"],
          data: [
            [
              { startTime: "1:00 AM", intensity: 2 },
              { startTime: "2:00 AM", intensity: 1 },
              { startTime: "3:00 AM", intensity: 1 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 4 },
              { startTime: "7:00 AM", intensity: 1 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 2 },
              { startTime: "10:00 AM", intensity: 5 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 1 },
              { startTime: "1:00 pm", intensity: 1 },
              { startTime: "2:00 pm", intensity: 2 },
              { startTime: "3:00 pm", intensity: 5 },
              { startTime: "4:00 pm", intensity: 5 },
              { startTime: "5:00 pm", intensity: 2 },
              { startTime: "6:00 pm", intensity: 2 },
              { startTime: "7:00 pm", intensity: 2 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 5 },
              { startTime: "10:00 pm", intensity: 4 },
              { startTime: "11:00 pm", intensity: 2 },
              { startTime: "12:00 pm", intensity: 0 },
            ],
            [
              { startTime: "1:00 AM", intensity: 0 },
              { startTime: "2:00 AM", intensity: 0 },
              { startTime: "3:00 AM", intensity: 0 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 0 },
              { startTime: "7:00 AM", intensity: 0 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 0 },
              { startTime: "10:00 AM", intensity: 0 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 0 },
              { startTime: "1:00 pm", intensity: 0 },
              { startTime: "2:00 pm", intensity: 0 },
              { startTime: "3:00 pm", intensity: 0 },
              { startTime: "4:00 pm", intensity: 0 },
              { startTime: "5:00 pm", intensity: 0 },
              { startTime: "6:00 pm", intensity: 0 },
              { startTime: "7:00 pm", intensity: 0 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 0 },
              { startTime: "10:00 pm", intensity: 0 },
              { startTime: "11:00 pm", intensity: 0 },
              { startTime: "12:00 pm", intensity: 0 },
            ],
            [
              { startTime: "1:00 AM", intensity: 0 },
              { startTime: "2:00 AM", intensity: 0 },
              { startTime: "3:00 AM", intensity: 0 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 0 },
              { startTime: "7:00 AM", intensity: 0 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 0 },
              { startTime: "10:00 AM", intensity: 0 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 0 },
              { startTime: "1:00 pm", intensity: 0 },
              { startTime: "2:00 pm", intensity: 0 },
              { startTime: "3:00 pm", intensity: 0 },
              { startTime: "4:00 pm", intensity: 0 },
              { startTime: "5:00 pm", intensity: 0 },
              { startTime: "6:00 pm", intensity: 0 },
              { startTime: "7:00 pm", intensity: 0 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 0 },
              { startTime: "10:00 pm", intensity: 0 },
              { startTime: "11:00 pm", intensity: 0 },
              { startTime: "12:00 pm", intensity: 0 },
            ],
            [
              { startTime: "1:00 AM", intensity: 0 },
              { startTime: "2:00 AM", intensity: 0 },
              { startTime: "3:00 AM", intensity: 0 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 0 },
              { startTime: "7:00 AM", intensity: 0 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 0 },
              { startTime: "10:00 AM", intensity: 0 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 0 },
              { startTime: "1:00 pm", intensity: 0 },
              { startTime: "2:00 pm", intensity: 0 },
              { startTime: "3:00 pm", intensity: 0 },
              { startTime: "4:00 pm", intensity: 0 },
              { startTime: "5:00 pm", intensity: 0 },
              { startTime: "6:00 pm", intensity: 0 },
              { startTime: "7:00 pm", intensity: 0 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 0 },
              { startTime: "10:00 pm", intensity: 0 },
              { startTime: "11:00 pm", intensity: 0 },
              { startTime: "12:00 pm", intensity: 0 },
            ],
            [
              { startTime: "1:00 AM", intensity: 0 },
              { startTime: "2:00 AM", intensity: 0 },
              { startTime: "3:00 AM", intensity: 0 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 2 },
              { startTime: "6:00 AM", intensity: 2 },
              { startTime: "7:00 AM", intensity: 2 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 0 },
              { startTime: "10:00 AM", intensity: 0 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 3 },
              { startTime: "1:00 pm", intensity: 3 },
              { startTime: "2:00 pm", intensity: 3 },
              { startTime: "3:00 pm", intensity: 0 },
              { startTime: "4:00 pm", intensity: 0 },
              { startTime: "5:00 pm", intensity: 0 },
              { startTime: "6:00 pm", intensity: 0 },
              { startTime: "7:00 pm", intensity: 0 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 3 },
              { startTime: "10:00 pm", intensity: 3 },
              { startTime: "11:00 pm", intensity: 3 },
              { startTime: "12:00 pm", intensity: 3 },
            ],
            [
              { startTime: "1:00 AM", intensity: 0 },
              { startTime: "2:00 AM", intensity: 0 },
              { startTime: "3:00 AM", intensity: 0 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 0 },
              { startTime: "7:00 AM", intensity: 0 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 0 },
              { startTime: "10:00 AM", intensity: 0 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 0 },
              { startTime: "1:00 pm", intensity: 0 },
              { startTime: "2:00 pm", intensity: 0 },
              { startTime: "3:00 pm", intensity: 0 },
              { startTime: "4:00 pm", intensity: 0 },
              { startTime: "5:00 pm", intensity: 0 },
              { startTime: "6:00 pm", intensity: 0 },
              { startTime: "7:00 pm", intensity: 0 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 0 },
              { startTime: "10:00 pm", intensity: 0 },
              { startTime: "11:00 pm", intensity: 0 },
              { startTime: "12:00 pm", intensity: 0 },
            ],
            [
              { startTime: "1:00 AM", intensity: 0 },
              { startTime: "2:00 AM", intensity: 0 },
              { startTime: "3:00 AM", intensity: 0 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 0 },
              { startTime: "7:00 AM", intensity: 0 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 0 },
              { startTime: "10:00 AM", intensity: 0 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 0 },
              { startTime: "1:00 pm", intensity: 0 },
              { startTime: "2:00 pm", intensity: 0 },
              { startTime: "3:00 pm", intensity: 0 },
              { startTime: "4:00 pm", intensity: 0 },
              { startTime: "5:00 pm", intensity: 0 },
              { startTime: "6:00 pm", intensity: 0 },
              { startTime: "7:00 pm", intensity: 0 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 0 },
              { startTime: "10:00 pm", intensity: 0 },
              { startTime: "11:00 pm", intensity: 0 },
              { startTime: "12:00 pm", intensity: 0 },
            ],
            [
              { startTime: "1:00 AM", intensity: 0 },
              { startTime: "2:00 AM", intensity: 0 },
              { startTime: "3:00 AM", intensity: 0 },
              { startTime: "4:00 AM", intensity: 0 },
              { startTime: "5:00 AM", intensity: 0 },
              { startTime: "6:00 AM", intensity: 0 },
              { startTime: "7:00 AM", intensity: 0 },
              { startTime: "8:00 AM", intensity: 0 },
              { startTime: "9:00 AM", intensity: 0 },
              { startTime: "10:00 AM", intensity: 0 },
              { startTime: "11:00 AM", intensity: 0 },
              { startTime: "12:00 AM", intensity: 0 },
              { startTime: "1:00 pm", intensity: 0 },
              { startTime: "2:00 pm", intensity: 0 },
              { startTime: "3:00 pm", intensity: 0 },
              { startTime: "4:00 pm", intensity: 0 },
              { startTime: "5:00 pm", intensity: 0 },
              { startTime: "6:00 pm", intensity: 0 },
              { startTime: "7:00 pm", intensity: 0 },
              { startTime: "8:00 pm", intensity: 0 },
              { startTime: "9:00 pm", intensity: 0 },
              { startTime: "10:00 pm", intensity: 0 },
              { startTime: "11:00 pm", intensity: 0 },
              { startTime: "12:00 pm", intensity: 0 },
            ],
          ],
        };
      default:
        return {
          label: [
            "Label",
            dayLabel(new Date(crying_data[0]?.date).getDay()),
            dayLabel(new Date(crying_data[1]?.date).getDay()),
            dayLabel(new Date(crying_data[2]?.date).getDay()),
            dayLabel(new Date(crying_data[3]?.date).getDay()),
            dayLabel(new Date(crying_data[4]?.date).getDay()),
            dayLabel(new Date(crying_data[5]?.date).getDay()),
            dayLabel(new Date(crying_data[6]?.date).getDay()),
          ],
          data: weeklyData,
        };
    }
  };

  const styleValue = (arg, i, ind, styles) => {
    if (i !== 0) {
      switch (arg[ind].intensity) {
        case 0:
          return styles.valueNone;
        case 1:
          return styles.valueOne;

        case 2:
          return styles.valueTwo;
        case 3:
          return styles.valueThree;
        case 4:
          return styles.valueFour;
        case 5:
          return styles.valueFive;
      }
    } else {
      return styles.valueLabel;
    }
  };

  return (
    <HomePage
      day={day}
      setDay={setDay}
      labelByDay={labelByDay}
      styleValue={styleValue}
      profileDetail={profileDetail}
      {...props}
    />
  );
};
